export enum RouteNames {
  // Slug routes
  METRICS = 'metrics',
  HEALTH = 'health',
  AUTH = 'auth',
  API_DOCS = 'api',
  QUEUES_UI = 'queues',
  LISTING = 'listings',
  EXTERNAL_SERVICES = 'external-services',
  EMAIL = 'email',
  CHAT = 'chat',
  AUDIT_LOGS = 'audit-logs',
  MEDIA_UPLOAD = 'media-upload',
  PAYMENT = 'payment',
  PLACES = 'places',
  PROPERTY_MANAGEMENT = 'property-management',
  PROPERTY_OFFERS = 'property-offers',
  SMS = 'SMS',
  STATIC = 'static',
  SUPPORT = 'support',
  USERS = 'users',
  WEBSOCKET_DOCS = 'websocket-docs',
  SERVICE_REQUESTS = 'service-requests',
  FLAG_MANAGEMENT = 'flag-management',
  ANALYTICS = 'analytics',
  FORUMS = 'forums',
  NOTIFICATIONS = 'notifications',
  DEV_TOOLS = 'dev-tools',
  HEALTH_UI = 'health-ui',

  // Named routes
  // --- METRICS ROUTES ---
  INCREMENT = 'increment',
  ACTIVE_USERS = 'active-users',

  // --- AUTH ROUTES ---
  AUTH_LOGIN = 'login',
  AUTH_LOGOUT = 'logout',
  AUTH_REGISTER = 'register',
  AUTH_REGISTRATION_OTP = 'registration-otp',
  AUTH_RESET_PASSWORD = 'reset-password',
  AUTH_SET_PASSWORD = 'set-password',
  AUTH_FORGOT_PASSWORD = 'forgot-password',
  AUTH_OTP_VERIFY = 'otp-verify',
  AUTH_GOOGLE = 'google',
  AUTH_GOOGLE_REDIRECT = 'google/redirect',
  AUTH_FACEBOOK = 'facebook',
  AUTH_FACEBOOK_REDIRECT = 'facebook/redirect',
  AUTH_APPLE = 'apple',
  AUTH_APPLE_REDIRECT = 'apple/redirect',
  AUTH_REFRESH_JWT_TOKEN = 'refresh-jwt-token',
  AUTH_LOGGED_IN_USER = 'logged-in-user',
  AUTH_VERIFY_USERNAME = 'verify-username',
  AUTH_NOTIFICATION_TOKEN = 'notification-token',

  // --- LISTING ROUTES ---
  LISTING_COUNT_BY_PRICE_RANGE = 'count-by-price-range',
  LISTING_COUNT_BY_AREA_RANGE = 'count-by-area-range',
  LISTING_UPLOAD_MEDIA = 'upload-media',
  LISTING_DELETE_MEDIA = 'delete-media',
  LISTING_UPSERT_VIDEO_LINK = 'upsert-video-link',
  LISTING_SEARCH = 'search',
  LISTING_GENERATE_LISTING_DETAILS = 'generate-listing-details/:listingId',
  LISTING_PUBLISH = 'publish/:listingId',
  LISTING_ADD_LISTING = 'add-listing',
  LISTING_GENERATE_NEW_LISTING = 'generate-new-listing',
  LISTING_BOOSTING_CHECKOUT = ':listingId/boosting/:planId/checkout',
  LISTING_SUBSCRIPTION_PLANS = ':id/subscriptions-plans',
  LISTING_FAVORITE = ':listingId/favorite',
  LISTING_SHARE = ':listingId/share',
  LISTING_COMMENT = ':listingId/comment',
  LISTING_COMMENTS = ':listingId/comments',
  LISTING_COMMENT_REACTION = ':listingId/comments/:commentId/reaction',
  LISTING_DELETE_COMMENT = ':listingId/comments/:commentId',
  LISTING_GET_COMMENTS = ':listingId/comments',
  LISTING_MEDIA_ORDER = ':listingId/media/order',
  LISTING_BOOSTING_ORDER = ':listingId/boosting/:planId/order',
  LISTING_BOOSTING_UPGRADE = ':listingId/boosting/:planId/upgrade',
  LISTING_BOOKING_CANCEL = ':listingId/boosting/cancel',
  LISTING_BOOSTING_REMOVE_REQUEST = ':listingId/boosting/remove-request',
  LISTING_AUCTION_BID = ':listingId/auction/bid',
  LISTING_AUCTION_BID_INCREMENT = ':listingId/auction/:bidId/bid-increment',
  LISTING_AUCTION_WITHDRAW_BID = ':listingId/auction/:bidId/withdraw-bid',
  LISTING_AUCTION_ACCEPT_BID = ':listingId/auction/:bidId/accept-bid',
  LISTING_AUCTION_UPLOAD_DOCUMENT = ':listingId/auction/upload-document',
  LISTING_AUCTION_WINNING_BID = ':listingId/auction/winning-bid',
  LISTING_AUCTION_CLOSE = ':listingId/auction/close',
  LISTING_AUCTION_BIDS = ':listingId/auction/bids',
  LISTING_FAVORITES = 'favorites',
  LISTING_MY_LISTINGS = 'my-listings',
  LISTING_SAVED_DRAFTS = 'saved-drafts',
  LISTING_DISABLE_ENABLE = ':listingId/:disable',
  LISTING_DELETE = ':listingId',
  LISTING_MY_BIDS = 'my-bids',
  LISTING_HOME = 'home',
  LISTING_FEATURED = 'featured',
  LISTING_ACCEPT_INVITE = ':listingId/accept-invite',
  LISTING_UPDATE = ':listingId',
  LISTING_SIMILAR = ':listingId/similar',
  LISTING_AUCTION_EXTEND = ':listingId/auction/extend',
  LISTING_MY_OFFERS = 'my-offers',
  LISTING_DETAILS = ':listingId',
  LISTING_UPDATE_MEDIA = ':listingId/media',
  LISTINGS_OF_USERS_USER_ID = 'users/:userId/listings',
  LISTING_DUPLICATE = ':listingId/duplicate',

  LISTING_ADD_COSELLER = ':listingId/co-seller',
  LISTING_UPDATE_ACTIVITY = ':listingId/activity',

  // --- EXTERNAL SERVICES ROUTES ---
  EXTERNAL_SERVICE_PROVIDERS = 'providers',
  EXTERNAL_SERVICE_CATEGORIES = 'categories',
  EXTERNAL_SERVICE_ADMIN_CATEGORIES = 'admin/categories',
  EXTERNAL_SERVICE_GENERATE_SERVICE_PROVIDER_ID = 'generate-service-provider-id',
  EXTERNAL_SERVICE_CREATE_SERVICE_PROVIDER = 'providers/:providerId',
  EXTERNAL_SERVICE_CREATE_SERVICE = 'providers/:providerId/services',
  EXTERNAL_SERVICE_CREATE_BANK_DETAILS = 'providers/:providerId/connected-account',
  EXTERNAL_SERVICE_REVALIDATE_CONNECTED_ACCOUNT = 'providers/:providerId/revalidate-connected-account',
  EXTERNAL_SERVICE_UPDATE_CATEGORY_STATUS = 'categories',
  EXTERNAL_SERVICE_UPDATE_PROVIDER_STATUS = 'service-providers/:providerId',
  EXTERNAL_SERVICE_UPDATE_SERVICE_STATUS = 'services/:serviceId',
  EXTERNAL_SERVICE_GET_ALL_ADDED_SERVICES_FOR_PROVIDER = 'providers/:providerId/addedServices',
  EXTERNAL_SERVICE_GET_SERVICE_PROVIDER_BY_ID = 'service-providers/:providerId',
  EXTERNAL_SERVICE_GET_BANK_DETAILS = 'service-providers/:providerId/bank-details',
  EXTERNAL_SERVICE_UPLOAD_MEDIA = 'upload-media',
  EXTERNAL_SERVICE_CREATE_CATEGORY = 'categories',
  EXTERNAL_SERVICE_SEARCH_BUSINESSES = 'service-management',
  EXTERNAL_SERVICE_SEARCH_CATEGORIES = 'service-management/categories',
  EXTERNAL_SERVICE_DELETE_PROVIDER = 'service-providers/:providerId',
  EXTERNAL_SERVICE_DELETE_CATEGORY = 'categories/:categoryId',
  EXTERNAL_SERVICE_DELETE_SERVICE = 'service-providers/:providerId/services/:serviceId',
  EXTERNAL_SERVICE_GET_ALL_SERVICES_BY_PROVIDER_ID = 'service-management/providers/:providerId/services',
  EXTERNAL_SERVICE_UPLOAD_PROVIDER_MEDIA = 'providers/:providerId/upload-media',
  EXTERNAL_SERVICE_GET_ALL_SERVICE_TAGS = 'service-tags',
  EXTERNAL_SERVICE_GET_ALL_SERVICE_BY_PROVIDER_ID = 'providers/:providerId/services',

  // --- EMAIL ROUTES ---
  EMAIL_SEND = 'send',

  // --- CHAT ROUTES ---
  CHAT_CREATE_USER_CHAT = 'user/:participantId',
  CHAT_LISTING = 'listing',
  CHAT_UPDATE_PARTICIPATION = ':id/participation',
  CHAT_UNREAD_CHATS_AVAILABLE = 'unread',
  CHAT_FILTERS = 'filters',
  CHAT_USERS = 'users',
  CHAT_MESSAGES = ':id/messages',
  CHAT_DETAILS = ':id',
  CHAT_LINK_PREVIEW = 'link-preview',
  CHAT_REMOVE_PARTICIPANT = ':id/participants',
  CHAT_ADD_PARTICIPANTS = ':id/participants',
  CHAT_MESSAGE_READ = ':id/messages/read',
  CHAT_UPDATE_SETTINGS = ':id/settings',

  // --- MEDIA UPLOAD ROUTES ---
  MEDIA_UPLOAD_UPLOAD = 'upload',
  MEDIA_UPLOAD_DELETE = 'delete',
  MEDIA_UPLOAD_LIST = 'list',
  MEDIA_UPLOAD_GET = 'get',

  // --- PAYMENT ROUTES ---
  PAYMENT_WEBHOOK = 'webhooks',
  PAYMENT_CONNECT_ACCOUNT_WEBHOOK = 'connect-account-webhooks',
  PAYMENT_GET_TRANSACTION_STATUS = 'status/:transactionId',
  PAYMENT_TRANSACTIONS = 'transactions',
  PAYMENT_MY_TRANSACTIONS = 'my-transactions',
  PAYMENT_INVOICE_VIEW = 'invoice/:transactionId/view',
  PAYMENT_INVOICE_DOWNLOAD = 'invoice/:transactionId/download',

  // --- PLACES ROUTES ---
  PLACES_REVERSE_GEOCODE = 'reverse-geocode',
  PLACES_PLACE_BY_ADDRESS = 'place-by-address',

  // --- PROPERTY MANAGEMENT ROUTES ---
  PROPERTY_MANAGEMENT_LISTINGS = 'listings',
  PROPERTY_MANAGEMENT_SUBSCRIPTION_BOOSTING = ':listingId/subscription-boosting/:planId',
  PROPERTY_MANAGEMENT_BULK_UPLOAD_LISTINGS = 'bulk-upload-listings',
  PROPERTY_MANAGEMENT_PRESIGNED_URL = 'presigned-url',
  PROPERTY_MANAGEMENT_DUPLICATE = ':listingId/duplicate',
  PROPERTY_MANAGEMENT_STATIC_DATA = 'static-data',
  PROPERTY_MANAGEMENT_PLAN_PRICE_UPDATE = '/plan-price-update/:planId',

  // --- PROPERTY OFFERS ROUTES ---
  PROPERTY_OFFERS_MAKE_AN_OFFER = ':listingId',
  PROPERTY_OFFERS_COUNTER_OFFER = ':listingId/counter-offer/:offerId',
  PROPERTY_OFFERS_UPDATE_OFFER = ':listingId/offer/:offerId',
  PROPERTY_OFFERS_ACCEPTANCE = ':listingId/offer/:offerId/acceptance',
  PROPERTY_OFFERS_DOCUMENT_DETAILS = ':listingId/offer/:offerId/document-details',
  PROPERTY_OFFERS_UPLOAD_DOCUMENT = ':listingId/offer/:offerId/upload-document',

  // --- SMS ROUTES ---
  SMS_SEND = 'send',

  // --- STATIC ROUTES ---
  STATIC_INTERESTS = 'interests',
  STATIC_PROPERTY_TAGS = 'property-tags',
  STATIC_AMENITIES = 'amenties',
  STATIC_METADATA_CATEGORIES = 'metadata-categories/:type',
  STATIC_BOOSTING_PLANS = 'boosting-plans',
  STATIC_PUBLIC_POST_CATEGORIES = 'forum-categories',
  STATIC_PUBLIC_POST_CITIES = 'forum-cities',

  // --- SUPPORT ROUTES ---
  SUPPORT_GET_TICKET = ':ticketId',
  SUPPORT_UPDATE_TICKET = ':ticketId/status',
  SUPPORT_ASSIGN_TICKET = ':ticketId/assign',

  // --- USERS ROUTES ---
  USERS_ONBOARDING_UPLOAD_AVATAR = 'onboarding/avatar',
  USERS_ONBOARDING_DELETE_AVATAR = 'onboarding/avatar',
  USERS_ONBOARDING_GET_PROFILE = 'onboarding/profile',
  USERS_ONBOARDING_UPDATE_PROFILE = 'onboarding/profile',
  USERS_ONBOARDING_UPSERT_PRIMARY_PREFERENCE = 'onboarding/user-primary-preferences',
  USERS_ONBOARDING_GET_USER_PRIMARY_PREFERENCE = 'onboarding/user-primary-preferences',
  USERS_PROFILE = 'profile',
  USERS_PREFERENCES = 'preferences',
  USERS_SEARCH = 'search',
  USERS_CONSENT = 'consent',
  USERS_AVATAR = 'avatar',
  USERS_GET_USER_DETAILS = ':userId',
  USERS_USERS_MANAGEMENT = 'user-management',
  USERS_MANAGEMENT_MANAGE_USERS = 'user-management/manage-users',
  USERS_MANAGEMENT_MANAGE_USER = 'user-management/manage-users/:userId',
  USERS_MANAGEMENT_PROFILE_VERIFICATION = 'user-management/profile-verification',
  USERS_MANAGEMENT_PROFILE_VERIFICATION_BY_ID = 'user-management/profile-verification/:verificationId',
  USERS_MANAGEMENT_VERIFY_DOCUMENT = 'user-management/verify-document/:userId',
  USERS_MANAGEMENT_REVOKE_DOCUMENT = 'user-management/revoke-document/:userId',
  USERS_MANAGEMENT_MANAGE_USERS_INSIGHTS = 'user-management/manage-users/insights',
  USERS_UPLOAD_MEDIA = 'upload-media',
  USERS_DELETE_MEDIA = 'delete-media',
  USERS_UPDATE_CONTACT = 'update-contact',
  USERS_VERIFY_CONTACT = 'verify-contact',
  USERS_RESET_PASSWORD = 'reset-password',
  USERS_ADMIN_DELETE_ACCOUNT = 'admin/user',
  USERS_UPDATE_USERNAME_ADMIN = 'admin/update-username',
  USERS_UPDATE_USERNAME = 'update-username',
  USERS_PERMISSIONS = 'permissions',
  USERS_USER_PROFILE_DETAILS = ':userId/profile',
  USERS_USER_CONSENT_WEBHOOK = 'consent-webhook',
  USERS_CONSENT_ACCEPT = 'consent-accept',

  // --- WEBSOCKET ROUTES ---
  WEBSOCKET_DOCS_SEND_MESSAGE = 'send-message',
  WEBSOCKET_DOCS_INITIATE_MEDIA_UPLOAD = 'initiate-media-upload',
  WEBSOCKET_DOCS_TYPING = 'typing',
  WEBSOCKET_DOCS_JOIN_ROOM = 'join-room',
  WEBSOCKET_DOCS_LEAVE_ROOM = 'leave-room',

  SERVICE_REQUESTS_ADD_SERVICE_TO_CART = 'cart/:service_id',
  SERVICE_REQUESTS_DELETE_SERVICE_FROM_CART = 'cart/:service_id',
  SERVICE_REQUESTS_GET_CART_DETIALS = 'cart',
  SERVICE_REQUESTS_UPDATE_BOOKING_DETAILS = 'cart',
  SERVICE_REQUESTS_INITIATE_PAYMENT = 'checkout/initiate-payment',
  SERVICE_REQUESTS_CANCEL_SERVICE_REQUEST = ':serviceRequestId',
  SERVICE_REQUESTS_CREATE_REVIEW = ':serviceRequestID',
  SERVICE_REQUESTS_GET_USER_SERVICE_REQUESTS = 'user',
  SERVICE_REQUESTS_GET_STATS = 'stats',
  SERVICE_REQUESTS_GET_DETAILS = ':serviceRequestID',
  SERVICE_REQUESTS_INITIATE_REFUND = 'initiate-refund',
  SERVICE_REQUESTS_REFUND_REQUEST_DETAILS = 'service-request/refund-request-details',
  SERVICE_REQUESTS_GET_INVOICE = 'generate-invoice/:serviceRequestId',
  SERVICE_REQUESTS_BOOKING_DETAILS = 'booking-details/:serviceRequestId',
  SERVICE_REQUESTS_PAYMENT_STATUS = 'payment-status/:serviceRequestId',
  SERVICE_REQUESTS_HISTORY = 'service-requests/:serviceRequestId/history',
  SERVICE_REQUESTS_RETRY_PAYOUT = 'retry-payout/:serviceRequestId',
  SERVICE_REQUESTS_CHECK_PAYOUT_REFUND_STATUS = 'check-payout-refund-status/:serviceRequestId',
  // --- FLAG MANAGEMENT ROUTES ---
  FLAG_MANAGEMENT_REPORT_LISTING_COMMENT_REPLY = 'report-listing-comment-reply',
  FLAG_MANAGEMENT_REPORT_LISTING = 'report-listing',
  FLAG_MANAGEMENT_REPORT_USER = 'report-user',
  FLAG_MANAGEMENT_REPORT_CHAT_CONVERSATION = 'report-chat-conversation',
  FLAG_MANAGEMENT_REPORT_CHAT_MESSAGE = 'report-chat-message',
  FLAG_MANAGEMENT_REPORT_PUBLIC_POST = 'report-public-post',
  FLAG_MANAGEMENT_REPORT_PUBLIC_POST_COMMENT = 'report-public-post-comment',
  FLAG_MANAGEMENT_REPORTED_DETAILS_BY_ID = ':id',
  FLAG_MANAGEMENT_DISABLE_BY_ID = ':id/:disable',

  // --- ANALYTICS ROUTES ---
  ANALYTICS_DASHBOARD_SUMMARY = 'dashboard-summary',

  // --- FORUMS ROUTES ---
  GET_POST = ':postId',
  DELETE_POST = ':postId',
  SHARE_POST = ':postId/share',
  REACT_TO_POST = ':postId/react',
  POST_COMMENT = ':postId/comment',
  GET_COMMENTS = ':postId/comments',
  REACT_TO_COMMENT = ':postId/comments/:commentId/react',
  DELETE_COMMENT = ':postId/comments/:commentId',
  GET_POSTS = 'posts',

  // --- NOTIFICATIONS ROUTES ---
  NOTIFICATIONS_READ = 'read/:notificationId',
}
