/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssessmentListApiResponse,
  CompleteAssessmentApiResponse,
  ModelApiResponse,
  StartAssessmentApiResponse,
  StartAssessmentBodyDto,
  StoreAnswerDto,
  UpsertAssessmentApiResponse,
  UpsertAssessmentDto,
  UserAssessmentListApiResponse,
} from '../models/index';
import {
    AssessmentListApiResponseFromJSON,
    AssessmentListApiResponseToJSON,
    CompleteAssessmentApiResponseFromJSON,
    CompleteAssessmentApiResponseToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    StartAssessmentApiResponseFromJSON,
    StartAssessmentApiResponseToJSON,
    StartAssessmentBodyDtoFromJSON,
    StartAssessmentBodyDtoToJSON,
    StoreAnswerDtoFromJSON,
    StoreAnswerDtoToJSON,
    UpsertAssessmentApiResponseFromJSON,
    UpsertAssessmentApiResponseToJSON,
    UpsertAssessmentDtoFromJSON,
    UpsertAssessmentDtoToJSON,
    UserAssessmentListApiResponseFromJSON,
    UserAssessmentListApiResponseToJSON,
} from '../models/index';

export interface AssessmentsControllerCompleteAssessmentRequest {
    userAssessmentId: string;
}

export interface AssessmentsControllerGetAssessmentDetailsRequest {
    assessmentId: string;
}

export interface AssessmentsControllerGetAssessmentsListRequest {
    type?: AssessmentsControllerGetAssessmentsListTypeEnum;
    courseId?: string;
    difficulty?: AssessmentsControllerGetAssessmentsListDifficultyEnum;
    page?: number;
    limit?: number;
    draftAssessment?: AssessmentsControllerGetAssessmentsListDraftAssessmentEnum;
}

export interface AssessmentsControllerGetUserAssessmentCompleteDataRequest {
    userAssessmentId: string;
}

export interface AssessmentsControllerGetUserAssessmentsRequest {
    type?: AssessmentsControllerGetUserAssessmentsTypeEnum;
    courseId?: string;
    difficulty?: AssessmentsControllerGetUserAssessmentsDifficultyEnum;
    status?: Array<AssessmentsControllerGetUserAssessmentsStatusEnum>;
    page?: number;
    limit?: number;
}

export interface AssessmentsControllerPublishAssessmentRequest {
    assessmentId: string;
}

export interface AssessmentsControllerStartAssessmentRequest {
    startAssessmentBodyDto: StartAssessmentBodyDto;
}

export interface AssessmentsControllerStoreUserAnswersRequest {
    userAssessmentId: string;
    questionId: string;
    storeAnswerDto: StoreAnswerDto;
}

export interface AssessmentsControllerUpsertAssessmentRequest {
    upsertAssessmentDto: UpsertAssessmentDto;
}

/**
 * 
 */
export class AssessmentsApi extends runtime.BaseAPI {

    /**
     * Mark an assessment as completed and calculate final results
     * Complete an assessment
     */
    async assessmentsControllerCompleteAssessmentRaw(requestParameters: AssessmentsControllerCompleteAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompleteAssessmentApiResponse>> {
        if (requestParameters['userAssessmentId'] == null) {
            throw new runtime.RequiredError(
                'userAssessmentId',
                'Required parameter "userAssessmentId" was null or undefined when calling assessmentsControllerCompleteAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/user-assessment/{userAssessmentId}/complete`.replace(`{${"userAssessmentId"}}`, encodeURIComponent(String(requestParameters['userAssessmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompleteAssessmentApiResponseFromJSON(jsonValue));
    }

    /**
     * Mark an assessment as completed and calculate final results
     * Complete an assessment
     */
    async assessmentsControllerCompleteAssessment(requestParameters: AssessmentsControllerCompleteAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompleteAssessmentApiResponse> {
        const response = await this.assessmentsControllerCompleteAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get assessment details
     * Get assessment details
     */
    async assessmentsControllerGetAssessmentDetailsRaw(requestParameters: AssessmentsControllerGetAssessmentDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpsertAssessmentApiResponse>> {
        if (requestParameters['assessmentId'] == null) {
            throw new runtime.RequiredError(
                'assessmentId',
                'Required parameter "assessmentId" was null or undefined when calling assessmentsControllerGetAssessmentDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/{assessmentId}`.replace(`{${"assessmentId"}}`, encodeURIComponent(String(requestParameters['assessmentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpsertAssessmentApiResponseFromJSON(jsonValue));
    }

    /**
     * Get assessment details
     * Get assessment details
     */
    async assessmentsControllerGetAssessmentDetails(requestParameters: AssessmentsControllerGetAssessmentDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpsertAssessmentApiResponse> {
        const response = await this.assessmentsControllerGetAssessmentDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve assessments with optional filters for type, course_id, and difficulty. Supports pagination.
     * Get list of assessments with filtering and pagination
     */
    async assessmentsControllerGetAssessmentsListRaw(requestParameters: AssessmentsControllerGetAssessmentsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssessmentListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['courseId'] != null) {
            queryParameters['course_id'] = requestParameters['courseId'];
        }

        if (requestParameters['difficulty'] != null) {
            queryParameters['difficulty'] = requestParameters['difficulty'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['draftAssessment'] != null) {
            queryParameters['draft_assessment'] = requestParameters['draftAssessment'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/assessments/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssessmentListApiResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve assessments with optional filters for type, course_id, and difficulty. Supports pagination.
     * Get list of assessments with filtering and pagination
     */
    async assessmentsControllerGetAssessmentsList(requestParameters: AssessmentsControllerGetAssessmentsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssessmentListApiResponse> {
        const response = await this.assessmentsControllerGetAssessmentsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve complete assessment data including results and answers
     * Get completed assessment data
     */
    async assessmentsControllerGetUserAssessmentCompleteDataRaw(requestParameters: AssessmentsControllerGetUserAssessmentCompleteDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompleteAssessmentApiResponse>> {
        if (requestParameters['userAssessmentId'] == null) {
            throw new runtime.RequiredError(
                'userAssessmentId',
                'Required parameter "userAssessmentId" was null or undefined when calling assessmentsControllerGetUserAssessmentCompleteData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/user-assessment/{userAssessmentId}/complete-data`.replace(`{${"userAssessmentId"}}`, encodeURIComponent(String(requestParameters['userAssessmentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompleteAssessmentApiResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve complete assessment data including results and answers
     * Get completed assessment data
     */
    async assessmentsControllerGetUserAssessmentCompleteData(requestParameters: AssessmentsControllerGetUserAssessmentCompleteDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompleteAssessmentApiResponse> {
        const response = await this.assessmentsControllerGetUserAssessmentCompleteDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get paginated list of user assessments with optional filtering by type, course, difficulty, and status.
     * API to get user assessments list with filtering and pagination
     */
    async assessmentsControllerGetUserAssessmentsRaw(requestParameters: AssessmentsControllerGetUserAssessmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserAssessmentListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['courseId'] != null) {
            queryParameters['course_id'] = requestParameters['courseId'];
        }

        if (requestParameters['difficulty'] != null) {
            queryParameters['difficulty'] = requestParameters['difficulty'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/user-assessments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserAssessmentListApiResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated list of user assessments with optional filtering by type, course, difficulty, and status.
     * API to get user assessments list with filtering and pagination
     */
    async assessmentsControllerGetUserAssessments(requestParameters: AssessmentsControllerGetUserAssessmentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserAssessmentListApiResponse> {
        const response = await this.assessmentsControllerGetUserAssessmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish an assessment
     * Publish an assessment
     */
    async assessmentsControllerPublishAssessmentRaw(requestParameters: AssessmentsControllerPublishAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['assessmentId'] == null) {
            throw new runtime.RequiredError(
                'assessmentId',
                'Required parameter "assessmentId" was null or undefined when calling assessmentsControllerPublishAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/{assessmentId}/publish`.replace(`{${"assessmentId"}}`, encodeURIComponent(String(requestParameters['assessmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Publish an assessment
     * Publish an assessment
     */
    async assessmentsControllerPublishAssessment(requestParameters: AssessmentsControllerPublishAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.assessmentsControllerPublishAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If userAssessmentId is provided, checks existing assessment and returns questions if within duration. If assessmentId is provided, creates new user assessment with status in_progress and returns questions.
     * Start an assessment
     */
    async assessmentsControllerStartAssessmentRaw(requestParameters: AssessmentsControllerStartAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartAssessmentApiResponse>> {
        if (requestParameters['startAssessmentBodyDto'] == null) {
            throw new runtime.RequiredError(
                'startAssessmentBodyDto',
                'Required parameter "startAssessmentBodyDto" was null or undefined when calling assessmentsControllerStartAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/start`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartAssessmentBodyDtoToJSON(requestParameters['startAssessmentBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartAssessmentApiResponseFromJSON(jsonValue));
    }

    /**
     * If userAssessmentId is provided, checks existing assessment and returns questions if within duration. If assessmentId is provided, creates new user assessment with status in_progress and returns questions.
     * Start an assessment
     */
    async assessmentsControllerStartAssessment(requestParameters: AssessmentsControllerStartAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartAssessmentApiResponse> {
        const response = await this.assessmentsControllerStartAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Store user answers for a question
     * Store user answers
     */
    async assessmentsControllerStoreUserAnswersRaw(requestParameters: AssessmentsControllerStoreUserAnswersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userAssessmentId'] == null) {
            throw new runtime.RequiredError(
                'userAssessmentId',
                'Required parameter "userAssessmentId" was null or undefined when calling assessmentsControllerStoreUserAnswers().'
            );
        }

        if (requestParameters['questionId'] == null) {
            throw new runtime.RequiredError(
                'questionId',
                'Required parameter "questionId" was null or undefined when calling assessmentsControllerStoreUserAnswers().'
            );
        }

        if (requestParameters['storeAnswerDto'] == null) {
            throw new runtime.RequiredError(
                'storeAnswerDto',
                'Required parameter "storeAnswerDto" was null or undefined when calling assessmentsControllerStoreUserAnswers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/user-assessment/{userAssessmentId}/question/{questionId}`.replace(`{${"userAssessmentId"}}`, encodeURIComponent(String(requestParameters['userAssessmentId']))).replace(`{${"questionId"}}`, encodeURIComponent(String(requestParameters['questionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreAnswerDtoToJSON(requestParameters['storeAnswerDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Store user answers for a question
     * Store user answers
     */
    async assessmentsControllerStoreUserAnswers(requestParameters: AssessmentsControllerStoreUserAnswersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assessmentsControllerStoreUserAnswersRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new assessment or update an existing unpublished assessment with questions. Only unpublished assessments can be updated.
     * API to create or update assessment with questions (Admin only)
     */
    async assessmentsControllerUpsertAssessmentRaw(requestParameters: AssessmentsControllerUpsertAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpsertAssessmentApiResponse>> {
        if (requestParameters['upsertAssessmentDto'] == null) {
            throw new runtime.RequiredError(
                'upsertAssessmentDto',
                'Required parameter "upsertAssessmentDto" was null or undefined when calling assessmentsControllerUpsertAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/assessments/upsert`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertAssessmentDtoToJSON(requestParameters['upsertAssessmentDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpsertAssessmentApiResponseFromJSON(jsonValue));
    }

    /**
     * Create a new assessment or update an existing unpublished assessment with questions. Only unpublished assessments can be updated.
     * API to create or update assessment with questions (Admin only)
     */
    async assessmentsControllerUpsertAssessment(requestParameters: AssessmentsControllerUpsertAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpsertAssessmentApiResponse> {
        const response = await this.assessmentsControllerUpsertAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AssessmentsControllerGetAssessmentsListTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type AssessmentsControllerGetAssessmentsListTypeEnum = typeof AssessmentsControllerGetAssessmentsListTypeEnum[keyof typeof AssessmentsControllerGetAssessmentsListTypeEnum];
/**
 * @export
 */
export const AssessmentsControllerGetAssessmentsListDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type AssessmentsControllerGetAssessmentsListDifficultyEnum = typeof AssessmentsControllerGetAssessmentsListDifficultyEnum[keyof typeof AssessmentsControllerGetAssessmentsListDifficultyEnum];
/**
 * @export
 */
export const AssessmentsControllerGetAssessmentsListDraftAssessmentEnum = {
    True: 'true',
    False: 'false'
} as const;
export type AssessmentsControllerGetAssessmentsListDraftAssessmentEnum = typeof AssessmentsControllerGetAssessmentsListDraftAssessmentEnum[keyof typeof AssessmentsControllerGetAssessmentsListDraftAssessmentEnum];
/**
 * @export
 */
export const AssessmentsControllerGetUserAssessmentsTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type AssessmentsControllerGetUserAssessmentsTypeEnum = typeof AssessmentsControllerGetUserAssessmentsTypeEnum[keyof typeof AssessmentsControllerGetUserAssessmentsTypeEnum];
/**
 * @export
 */
export const AssessmentsControllerGetUserAssessmentsDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type AssessmentsControllerGetUserAssessmentsDifficultyEnum = typeof AssessmentsControllerGetUserAssessmentsDifficultyEnum[keyof typeof AssessmentsControllerGetUserAssessmentsDifficultyEnum];
/**
 * @export
 */
export const AssessmentsControllerGetUserAssessmentsStatusEnum = {
    Scheduled: 'scheduled',
    InProgress: 'in_progress',
    Completed: 'completed',
    Cancelled: 'cancelled',
    NoShow: 'no_show'
} as const;
export type AssessmentsControllerGetUserAssessmentsStatusEnum = typeof AssessmentsControllerGetUserAssessmentsStatusEnum[keyof typeof AssessmentsControllerGetUserAssessmentsStatusEnum];
