/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CoursesApiResponse,
} from '../models/index';
import {
    CoursesApiResponseFromJSON,
    CoursesApiResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class StaticDataApi extends runtime.BaseAPI {

    /**
     * API to get all active courses
     */
    async staticDataControllerGetActiveCoursesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoursesApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/static-data/courses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoursesApiResponseFromJSON(jsonValue));
    }

    /**
     * API to get all active courses
     */
    async staticDataControllerGetActiveCourses(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoursesApiResponse> {
        const response = await this.staticDataControllerGetActiveCoursesRaw(initOverrides);
        return await response.value();
    }

}
