/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUsersDto,
  AdminDashboardAnalyticsApiResponse,
  DisableUserDto,
  ModelApiResponse,
  UpdateUserProfileDto,
  UserAnalyticsApiResponse,
  UserIdDto,
  UserListApiResponse,
  UserProfileApiResponse,
  UserRankingApiResponse,
} from '../models/index';
import {
    AddUsersDtoFromJSON,
    AddUsersDtoToJSON,
    AdminDashboardAnalyticsApiResponseFromJSON,
    AdminDashboardAnalyticsApiResponseToJSON,
    DisableUserDtoFromJSON,
    DisableUserDtoToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    UpdateUserProfileDtoFromJSON,
    UpdateUserProfileDtoToJSON,
    UserAnalyticsApiResponseFromJSON,
    UserAnalyticsApiResponseToJSON,
    UserIdDtoFromJSON,
    UserIdDtoToJSON,
    UserListApiResponseFromJSON,
    UserListApiResponseToJSON,
    UserProfileApiResponseFromJSON,
    UserProfileApiResponseToJSON,
    UserRankingApiResponseFromJSON,
    UserRankingApiResponseToJSON,
} from '../models/index';

export interface UsersControllerAddUsersRequest {
    addUsersDto: AddUsersDto;
}

export interface UsersControllerDeleteUserRequest {
    userIdDto: UserIdDto;
}

export interface UsersControllerDisableUserRequest {
    disableUserDto: DisableUserDto;
}

export interface UsersControllerGetUserRankingRequest {
    page?: number;
    limit?: number;
}

export interface UsersControllerGetUsersListRequest {
    search?: string;
    status?: UsersControllerGetUsersListStatusEnum;
    page?: number;
    limit?: number;
}

export interface UsersControllerUpdateUserProfileRequest {
    updateUserProfileDto: UpdateUserProfileDto;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Add users by providing email addresses. Only emails that are not already in the database will be added.
     * API to add multiple users by email addresses (Admin only)
     */
    async usersControllerAddUsersRaw(requestParameters: UsersControllerAddUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['addUsersDto'] == null) {
            throw new runtime.RequiredError(
                'addUsersDto',
                'Required parameter "addUsersDto" was null or undefined when calling usersControllerAddUsers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddUsersDtoToJSON(requestParameters['addUsersDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Add users by providing email addresses. Only emails that are not already in the database will be added.
     * API to add multiple users by email addresses (Admin only)
     */
    async usersControllerAddUsers(requestParameters: UsersControllerAddUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.usersControllerAddUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API to get admin dashboard analytics
     */
    async usersControllerAdminDashboardAnalyticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminDashboardAnalyticsApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/admin/analytics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminDashboardAnalyticsApiResponseFromJSON(jsonValue));
    }

    /**
     * API to get admin dashboard analytics
     */
    async usersControllerAdminDashboardAnalytics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminDashboardAnalyticsApiResponse> {
        const response = await this.usersControllerAdminDashboardAnalyticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * API to delete a user (Admin only)
     */
    async usersControllerDeleteUserRaw(requestParameters: UsersControllerDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['userIdDto'] == null) {
            throw new runtime.RequiredError(
                'userIdDto',
                'Required parameter "userIdDto" was null or undefined when calling usersControllerDeleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: UserIdDtoToJSON(requestParameters['userIdDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * API to delete a user (Admin only)
     */
    async usersControllerDeleteUser(requestParameters: UsersControllerDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.usersControllerDeleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API to disable a user (Admin only)
     */
    async usersControllerDisableUserRaw(requestParameters: UsersControllerDisableUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['disableUserDto'] == null) {
            throw new runtime.RequiredError(
                'disableUserDto',
                'Required parameter "disableUserDto" was null or undefined when calling usersControllerDisableUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/disable`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DisableUserDtoToJSON(requestParameters['disableUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * API to disable a user (Admin only)
     */
    async usersControllerDisableUser(requestParameters: UsersControllerDisableUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.usersControllerDisableUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get individual user analytics including average score, rank, and last test taken time.
     * API to get user personal analytics
     */
    async usersControllerGetUserAnalyticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserAnalyticsApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/analytics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserAnalyticsApiResponseFromJSON(jsonValue));
    }

    /**
     * Get individual user analytics including average score, rank, and last test taken time.
     * API to get user personal analytics
     */
    async usersControllerGetUserAnalytics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserAnalyticsApiResponse> {
        const response = await this.usersControllerGetUserAnalyticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * API to get user profile with enrolled courses
     */
    async usersControllerGetUserProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileApiResponseFromJSON(jsonValue));
    }

    /**
     * API to get user profile with enrolled courses
     */
    async usersControllerGetUserProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileApiResponse> {
        const response = await this.usersControllerGetUserProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user ranking information including top performers and community statistics. Shows top 10 users and current user ranking.
     * API to get user ranking and community analytics
     */
    async usersControllerGetUserRankingRaw(requestParameters: UsersControllerGetUserRankingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRankingApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/ranking`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRankingApiResponseFromJSON(jsonValue));
    }

    /**
     * Get user ranking information including top performers and community statistics. Shows top 10 users and current user ranking.
     * API to get user ranking and community analytics
     */
    async usersControllerGetUserRanking(requestParameters: UsersControllerGetUserRankingRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRankingApiResponse> {
        const response = await this.usersControllerGetUserRankingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get paginated list of users with optional filtering by search term and active status. For admin use to manage users.
     * API to get users list with filtering and pagination (Admin only)
     */
    async usersControllerGetUsersListRaw(requestParameters: UsersControllerGetUsersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserListApiResponseFromJSON(jsonValue));
    }

    /**
     * Get paginated list of users with optional filtering by search term and active status. For admin use to manage users.
     * API to get users list with filtering and pagination (Admin only)
     */
    async usersControllerGetUsersList(requestParameters: UsersControllerGetUsersListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserListApiResponse> {
        const response = await this.usersControllerGetUsersListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * API to update user profile (full_name, gender, enrolled courses)
     */
    async usersControllerUpdateUserProfileRaw(requestParameters: UsersControllerUpdateUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileApiResponse>> {
        if (requestParameters['updateUserProfileDto'] == null) {
            throw new runtime.RequiredError(
                'updateUserProfileDto',
                'Required parameter "updateUserProfileDto" was null or undefined when calling usersControllerUpdateUserProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/users/profile`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserProfileDtoToJSON(requestParameters['updateUserProfileDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileApiResponseFromJSON(jsonValue));
    }

    /**
     * API to update user profile (full_name, gender, enrolled courses)
     */
    async usersControllerUpdateUserProfile(requestParameters: UsersControllerUpdateUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileApiResponse> {
        const response = await this.usersControllerUpdateUserProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const UsersControllerGetUsersListStatusEnum = {
    Disabled: 'disabled',
    Enabled: 'enabled'
} as const;
export type UsersControllerGetUsersListStatusEnum = typeof UsersControllerGetUsersListStatusEnum[keyof typeof UsersControllerGetUsersListStatusEnum];
