# version: '3.6'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - mAI_redis_data:/data
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}', # Enable password if provided
        '--appendonly',
        'yes', # Enable AOF for data persistence (optional)
      ]
    user: 'redis'
    networks:
      - mockai

volumes:
  mAI_redis_data:
    driver: local

networks:
  mockai:
    driver: bridge
