# version: '3.6'

services:
  postgres-db:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    volumes:
      - mAI_db_data:/var/lib/postgresql/data
    networks:
      - mockai

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - mAI_redis_data:/data
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD}', # Enable password if provided
        '--appendonly',
        'yes', # Enable AOF for data persistence (optional)
      ]
    user: 'redis'
    networks:
      - mockai

volumes:
  mAI_db_data:
    driver: local
  mAI_redis_data:
    driver: local

networks:
  mockai:
    driver: bridge
