/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddCourseRequestDto
 */
export interface AddCourseRequestDto {
    /**
     * Course name
     * @type {string}
     * @memberof AddCourseRequestDto
     */
    course: string;
}

/**
 * Check if a given object implements the AddCourseRequestDto interface.
 */
export function instanceOfAddCourseRequestDto(value: object): value is AddCourseRequestDto {
    if (!('course' in value) || value['course'] === undefined) return false;
    return true;
}

export function AddCourseRequestDtoFromJSON(json: any): AddCourseRequestDto {
    return AddCourseRequestDtoFromJSONTyped(json, false);
}

export function AddCourseRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCourseRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'course': json['course'],
    };
}

export function AddCourseRequestDtoToJSON(value?: AddCourseRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'course': value['course'],
    };
}

