/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUsersDto
 */
export interface AddUsersDto {
    /**
     * Array of email addresses to add as users
     * @type {Array<string>}
     * @memberof AddUsersDto
     */
    emails: Array<string>;
}

/**
 * Check if a given object implements the AddUsersDto interface.
 */
export function instanceOfAddUsersDto(value: object): value is AddUsersDto {
    if (!('emails' in value) || value['emails'] === undefined) return false;
    return true;
}

export function AddUsersDtoFromJSON(json: any): AddUsersDto {
    return AddUsersDtoFromJSONTyped(json, false);
}

export function AddUsersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUsersDto {
    if (json == null) {
        return json;
    }
    return {
        
        'emails': json['emails'],
    };
}

export function AddUsersDtoToJSON(value?: AddUsersDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emails': value['emails'],
    };
}

