/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminDashboardAnalyticResponse
 */
export interface AdminDashboardAnalyticResponse {
    /**
     * Total number of users
     * @type {number}
     * @memberof AdminDashboardAnalyticResponse
     */
    totalUsers: number;
    /**
     * Average score across all users (formatted as string)
     * @type {string}
     * @memberof AdminDashboardAnalyticResponse
     */
    averageScore: string;
    /**
     * Total number of assessments taken
     * @type {number}
     * @memberof AdminDashboardAnalyticResponse
     */
    totalAssessments: number;
    /**
     * Total number of questions across all assessments
     * @type {number}
     * @memberof AdminDashboardAnalyticResponse
     */
    totalQuestions: number;
}

/**
 * Check if a given object implements the AdminDashboardAnalyticResponse interface.
 */
export function instanceOfAdminDashboardAnalyticResponse(value: object): value is AdminDashboardAnalyticResponse {
    if (!('totalUsers' in value) || value['totalUsers'] === undefined) return false;
    if (!('averageScore' in value) || value['averageScore'] === undefined) return false;
    if (!('totalAssessments' in value) || value['totalAssessments'] === undefined) return false;
    if (!('totalQuestions' in value) || value['totalQuestions'] === undefined) return false;
    return true;
}

export function AdminDashboardAnalyticResponseFromJSON(json: any): AdminDashboardAnalyticResponse {
    return AdminDashboardAnalyticResponseFromJSONTyped(json, false);
}

export function AdminDashboardAnalyticResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDashboardAnalyticResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalUsers': json['totalUsers'],
        'averageScore': json['averageScore'],
        'totalAssessments': json['totalAssessments'],
        'totalQuestions': json['totalQuestions'],
    };
}

export function AdminDashboardAnalyticResponseToJSON(value?: AdminDashboardAnalyticResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalUsers': value['totalUsers'],
        'averageScore': value['averageScore'],
        'totalAssessments': value['totalAssessments'],
        'totalQuestions': value['totalQuestions'],
    };
}

