/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDashboardAnalyticResponse } from './AdminDashboardAnalyticResponse';
import {
    AdminDashboardAnalyticResponseFromJSON,
    AdminDashboardAnalyticResponseFromJSONTyped,
    AdminDashboardAnalyticResponseToJSON,
} from './AdminDashboardAnalyticResponse';

/**
 * 
 * @export
 * @interface AdminDashboardAnalyticsApiResponse
 */
export interface AdminDashboardAnalyticsApiResponse {
    /**
     * 
     * @type {number}
     * @memberof AdminDashboardAnalyticsApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardAnalyticsApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardAnalyticsApiResponse
     */
    message: string;
    /**
     * Admin dashboard analytics response data
     * @type {AdminDashboardAnalyticResponse}
     * @memberof AdminDashboardAnalyticsApiResponse
     */
    data?: AdminDashboardAnalyticResponse | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDashboardAnalyticsApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof AdminDashboardAnalyticsApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the AdminDashboardAnalyticsApiResponse interface.
 */
export function instanceOfAdminDashboardAnalyticsApiResponse(value: object): value is AdminDashboardAnalyticsApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AdminDashboardAnalyticsApiResponseFromJSON(json: any): AdminDashboardAnalyticsApiResponse {
    return AdminDashboardAnalyticsApiResponseFromJSONTyped(json, false);
}

export function AdminDashboardAnalyticsApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDashboardAnalyticsApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminDashboardAnalyticResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function AdminDashboardAnalyticsApiResponseToJSON(value?: AdminDashboardAnalyticsApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AdminDashboardAnalyticResponseToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

