/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssessmentResponseDto } from './AssessmentResponseDto';
import {
    AssessmentResponseDtoFromJSON,
    AssessmentResponseDtoFromJSONTyped,
    AssessmentResponseDtoToJSON,
} from './AssessmentResponseDto';
import type { PaginationDetailsDto } from './PaginationDetailsDto';
import {
    PaginationDetailsDtoFromJSON,
    PaginationDetailsDtoFromJSONTyped,
    PaginationDetailsDtoToJSON,
} from './PaginationDetailsDto';

/**
 * 
 * @export
 * @interface AssessmentListResponseDto
 */
export interface AssessmentListResponseDto {
    /**
     * List of assessments
     * @type {Array<AssessmentResponseDto>}
     * @memberof AssessmentListResponseDto
     */
    assessments: Array<AssessmentResponseDto>;
    /**
     * Pagination details
     * @type {PaginationDetailsDto}
     * @memberof AssessmentListResponseDto
     */
    pagination: PaginationDetailsDto;
}

/**
 * Check if a given object implements the AssessmentListResponseDto interface.
 */
export function instanceOfAssessmentListResponseDto(value: object): value is AssessmentListResponseDto {
    if (!('assessments' in value) || value['assessments'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AssessmentListResponseDtoFromJSON(json: any): AssessmentListResponseDto {
    return AssessmentListResponseDtoFromJSONTyped(json, false);
}

export function AssessmentListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'assessments': ((json['assessments'] as Array<any>).map(AssessmentResponseDtoFromJSON)),
        'pagination': PaginationDetailsDtoFromJSON(json['pagination']),
    };
}

export function AssessmentListResponseDtoToJSON(value?: AssessmentListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assessments': ((value['assessments'] as Array<any>).map(AssessmentResponseDtoToJSON)),
        'pagination': PaginationDetailsDtoToJSON(value['pagination']),
    };
}

