/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssessmentDetailsDto
 */
export interface AssessmentDetailsDto {
    /**
     * Assessment ID
     * @type {string}
     * @memberof AssessmentDetailsDto
     */
    id: string;
    /**
     * Assessment name
     * @type {string}
     * @memberof AssessmentDetailsDto
     */
    name: string;
    /**
     * Assessment type
     * @type {string}
     * @memberof AssessmentDetailsDto
     */
    type: AssessmentDetailsDtoTypeEnum;
    /**
     * Difficulty level
     * @type {string}
     * @memberof AssessmentDetailsDto
     */
    difficulty: AssessmentDetailsDtoDifficultyEnum;
    /**
     * Duration in minutes
     * @type {number}
     * @memberof AssessmentDetailsDto
     */
    duration_minutes: number;
    /**
     * Assessment description
     * @type {string}
     * @memberof AssessmentDetailsDto
     */
    description: string | null;
    /**
     * Maximum score
     * @type {number}
     * @memberof AssessmentDetailsDto
     */
    max_score: number;
    /**
     * Total number of questions
     * @type {number}
     * @memberof AssessmentDetailsDto
     */
    total_questions: number;
    /**
     * Course information
     * @type {object}
     * @memberof AssessmentDetailsDto
     */
    course: object | null;
}


/**
 * @export
 */
export const AssessmentDetailsDtoTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type AssessmentDetailsDtoTypeEnum = typeof AssessmentDetailsDtoTypeEnum[keyof typeof AssessmentDetailsDtoTypeEnum];

/**
 * @export
 */
export const AssessmentDetailsDtoDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type AssessmentDetailsDtoDifficultyEnum = typeof AssessmentDetailsDtoDifficultyEnum[keyof typeof AssessmentDetailsDtoDifficultyEnum];


/**
 * Check if a given object implements the AssessmentDetailsDto interface.
 */
export function instanceOfAssessmentDetailsDto(value: object): value is AssessmentDetailsDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('duration_minutes' in value) || value['duration_minutes'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('max_score' in value) || value['max_score'] === undefined) return false;
    if (!('total_questions' in value) || value['total_questions'] === undefined) return false;
    if (!('course' in value) || value['course'] === undefined) return false;
    return true;
}

export function AssessmentDetailsDtoFromJSON(json: any): AssessmentDetailsDto {
    return AssessmentDetailsDtoFromJSONTyped(json, false);
}

export function AssessmentDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'difficulty': json['difficulty'],
        'duration_minutes': json['duration_minutes'],
        'description': json['description'],
        'max_score': json['max_score'],
        'total_questions': json['total_questions'],
        'course': json['course'],
    };
}

export function AssessmentDetailsDtoToJSON(value?: AssessmentDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'difficulty': value['difficulty'],
        'duration_minutes': value['duration_minutes'],
        'description': value['description'],
        'max_score': value['max_score'],
        'total_questions': value['total_questions'],
        'course': value['course'],
    };
}

