/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssessmentListResponseDto } from './AssessmentListResponseDto';
import {
    AssessmentListResponseDtoFromJSON,
    AssessmentListResponseDtoFromJSONTyped,
    AssessmentListResponseDtoToJSON,
} from './AssessmentListResponseDto';

/**
 * 
 * @export
 * @interface AssessmentListApiResponse
 */
export interface AssessmentListApiResponse {
    /**
     * 
     * @type {number}
     * @memberof AssessmentListApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof AssessmentListApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AssessmentListApiResponse
     */
    message: string;
    /**
     * Assessment list data
     * @type {AssessmentListResponseDto}
     * @memberof AssessmentListApiResponse
     */
    data?: AssessmentListResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof AssessmentListApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof AssessmentListApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the AssessmentListApiResponse interface.
 */
export function instanceOfAssessmentListApiResponse(value: object): value is AssessmentListApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AssessmentListApiResponseFromJSON(json: any): AssessmentListApiResponse {
    return AssessmentListApiResponseFromJSONTyped(json, false);
}

export function AssessmentListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AssessmentListResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function AssessmentListApiResponseToJSON(value?: AssessmentListApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': AssessmentListResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

