/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityAnalyticsDto
 */
export interface CommunityAnalyticsDto {
    /**
     * Total number of users with scores
     * @type {number}
     * @memberof CommunityAnalyticsDto
     */
    total_users: number;
    /**
     * Community average score
     * @type {number}
     * @memberof CommunityAnalyticsDto
     */
    community_average_score?: number | null;
}

/**
 * Check if a given object implements the CommunityAnalyticsDto interface.
 */
export function instanceOfCommunityAnalyticsDto(value: object): value is CommunityAnalyticsDto {
    if (!('total_users' in value) || value['total_users'] === undefined) return false;
    return true;
}

export function CommunityAnalyticsDtoFromJSON(json: any): CommunityAnalyticsDto {
    return CommunityAnalyticsDtoFromJSONTyped(json, false);
}

export function CommunityAnalyticsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityAnalyticsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total_users': json['total_users'],
        'community_average_score': json['community_average_score'] == null ? undefined : json['community_average_score'],
    };
}

export function CommunityAnalyticsDtoToJSON(value?: CommunityAnalyticsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total_users': value['total_users'],
        'community_average_score': value['community_average_score'],
    };
}

