/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteAssessmentResponseDto } from './CompleteAssessmentResponseDto';
import {
    CompleteAssessmentResponseDtoFromJSON,
    CompleteAssessmentResponseDtoFromJSONTyped,
    CompleteAssessmentResponseDtoToJSON,
} from './CompleteAssessmentResponseDto';

/**
 * 
 * @export
 * @interface CompleteAssessmentApiResponse
 */
export interface CompleteAssessmentApiResponse {
    /**
     * 
     * @type {number}
     * @memberof CompleteAssessmentApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof CompleteAssessmentApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CompleteAssessmentApiResponse
     */
    message: string;
    /**
     * 
     * @type {CompleteAssessmentResponseDto}
     * @memberof CompleteAssessmentApiResponse
     */
    data?: CompleteAssessmentResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof CompleteAssessmentApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof CompleteAssessmentApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the CompleteAssessmentApiResponse interface.
 */
export function instanceOfCompleteAssessmentApiResponse(value: object): value is CompleteAssessmentApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CompleteAssessmentApiResponseFromJSON(json: any): CompleteAssessmentApiResponse {
    return CompleteAssessmentApiResponseFromJSONTyped(json, false);
}

export function CompleteAssessmentApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteAssessmentApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : CompleteAssessmentResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function CompleteAssessmentApiResponseToJSON(value?: CompleteAssessmentApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': CompleteAssessmentResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

