/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseDto } from './CourseDto';
import {
    CourseDtoFromJSON,
    CourseDtoFromJSONTyped,
    CourseDtoToJSON,
} from './CourseDto';

/**
 * 
 * @export
 * @interface CoursesResponseDto
 */
export interface CoursesResponseDto {
    /**
     * List of active courses
     * @type {Array<CourseDto>}
     * @memberof CoursesResponseDto
     */
    courses: Array<CourseDto>;
}

/**
 * Check if a given object implements the CoursesResponseDto interface.
 */
export function instanceOfCoursesResponseDto(value: object): value is CoursesResponseDto {
    if (!('courses' in value) || value['courses'] === undefined) return false;
    return true;
}

export function CoursesResponseDtoFromJSON(json: any): CoursesResponseDto {
    return CoursesResponseDtoFromJSONTyped(json, false);
}

export function CoursesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoursesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'courses': ((json['courses'] as Array<any>).map(CourseDtoFromJSON)),
    };
}

export function CoursesResponseDtoToJSON(value?: CoursesResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'courses': ((value['courses'] as Array<any>).map(CourseDtoToJSON)),
    };
}

