/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseDto
 */
export interface CourseDto {
    /**
     * Course ID
     * @type {string}
     * @memberof CourseDto
     */
    id: string;
    /**
     * Course name
     * @type {string}
     * @memberof CourseDto
     */
    name: string;
}

/**
 * Check if a given object implements the CourseDto interface.
 */
export function instanceOfCourseDto(value: object): value is CourseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CourseDtoFromJSON(json: any): CourseDto {
    return CourseDtoFromJSONTyped(json, false);
}

export function CourseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CourseDtoToJSON(value?: CourseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

