/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoursesResponseDto } from './CoursesResponseDto';
import {
    CoursesResponseDtoFromJSON,
    CoursesResponseDtoFromJSONTyped,
    CoursesResponseDtoToJSON,
} from './CoursesResponseDto';

/**
 * 
 * @export
 * @interface CoursesApiResponse
 */
export interface CoursesApiResponse {
    /**
     * 
     * @type {number}
     * @memberof CoursesApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof CoursesApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CoursesApiResponse
     */
    message: string;
    /**
     * 
     * @type {CoursesResponseDto}
     * @memberof CoursesApiResponse
     */
    data?: CoursesResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof CoursesApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof CoursesApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the CoursesApiResponse interface.
 */
export function instanceOfCoursesApiResponse(value: object): value is CoursesApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CoursesApiResponseFromJSON(json: any): CoursesApiResponse {
    return CoursesApiResponseFromJSONTyped(json, false);
}

export function CoursesApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoursesApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : CoursesResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function CoursesApiResponseToJSON(value?: CoursesApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': CoursesResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

