/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataDto
 */
export interface DataDto {
    /**
     * 
     * @type {string}
     * @memberof DataDto
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof DataDto
     */
    etag?: string;
    /**
     * 
     * @type {string}
     * @memberof DataDto
     */
    fileName?: string;
}

/**
 * Check if a given object implements the DataDto interface.
 */
export function instanceOfDataDto(value: object): value is DataDto {
    return true;
}

export function DataDtoFromJSON(json: any): DataDto {
    return DataDtoFromJSONTyped(json, false);
}

export function DataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'etag': json['etag'] == null ? undefined : json['etag'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
    };
}

export function DataDtoToJSON(value?: DataDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'etag': value['etag'],
        'fileName': value['fileName'],
    };
}

