/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataDto } from './DataDto';
import {
    DataDtoFromJSON,
    DataDtoFromJSONTyped,
    DataDtoToJSON,
} from './DataDto';

/**
 * 
 * @export
 * @interface DeleteMediaApiResponseDto
 */
export interface DeleteMediaApiResponseDto {
    /**
     * 
     * @type {number}
     * @memberof DeleteMediaApiResponseDto
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof DeleteMediaApiResponseDto
     */
    message: string;
    /**
     * 
     * @type {DataDto}
     * @memberof DeleteMediaApiResponseDto
     */
    data?: DataDto | null;
}

/**
 * Check if a given object implements the DeleteMediaApiResponseDto interface.
 */
export function instanceOfDeleteMediaApiResponseDto(value: object): value is DeleteMediaApiResponseDto {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteMediaApiResponseDtoFromJSON(json: any): DeleteMediaApiResponseDto {
    return DeleteMediaApiResponseDtoFromJSONTyped(json, false);
}

export function DeleteMediaApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMediaApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : DataDtoFromJSON(json['data']),
    };
}

export function DeleteMediaApiResponseDtoToJSON(value?: DeleteMediaApiResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'data': DataDtoToJSON(value['data']),
    };
}

