/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisableUserDto
 */
export interface DisableUserDto {
    /**
     * User ID
     * @type {string}
     * @memberof DisableUserDto
     */
    user_id: string;
    /**
     * Whether to disable the user
     * @type {boolean}
     * @memberof DisableUserDto
     */
    is_active: boolean;
}

/**
 * Check if a given object implements the DisableUserDto interface.
 */
export function instanceOfDisableUserDto(value: object): value is DisableUserDto {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    return true;
}

export function DisableUserDtoFromJSON(json: any): DisableUserDto {
    return DisableUserDtoFromJSONTyped(json, false);
}

export function DisableUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisableUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'is_active': json['is_active'],
    };
}

export function DisableUserDtoToJSON(value?: DisableUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_id': value['user_id'],
        'is_active': value['is_active'],
    };
}

