/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ForgotPasswordResponseDto } from './ForgotPasswordResponseDto';
import {
    ForgotPasswordResponseDtoFromJSON,
    ForgotPasswordResponseDtoFromJSONTyped,
    ForgotPasswordResponseDtoToJSON,
} from './ForgotPasswordResponseDto';

/**
 * 
 * @export
 * @interface ForgotPasswordApiResponse
 */
export interface ForgotPasswordApiResponse {
    /**
     * 
     * @type {number}
     * @memberof ForgotPasswordApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordApiResponse
     */
    message: string;
    /**
     * 
     * @type {ForgotPasswordResponseDto}
     * @memberof ForgotPasswordApiResponse
     */
    data?: ForgotPasswordResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof ForgotPasswordApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the ForgotPasswordApiResponse interface.
 */
export function instanceOfForgotPasswordApiResponse(value: object): value is ForgotPasswordApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ForgotPasswordApiResponseFromJSON(json: any): ForgotPasswordApiResponse {
    return ForgotPasswordApiResponseFromJSONTyped(json, false);
}

export function ForgotPasswordApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ForgotPasswordResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ForgotPasswordApiResponseToJSON(value?: ForgotPasswordApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': ForgotPasswordResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

