/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     * Email address to send OTP for password reset
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    email: string;
}

/**
 * Check if a given object implements the ForgotPasswordDto interface.
 */
export function instanceOfForgotPasswordDto(value: object): value is ForgotPasswordDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ForgotPasswordDtoFromJSON(json: any): ForgotPasswordDto {
    return ForgotPasswordDtoFromJSONTyped(json, false);
}

export function ForgotPasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ForgotPasswordDtoToJSON(value?: ForgotPasswordDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

