/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordResponseDto
 */
export interface ForgotPasswordResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponseDto
     */
    message: string;
    /**
     * Temporary token for password reset
     * @type {string}
     * @memberof ForgotPasswordResponseDto
     */
    temp_token: string;
}

/**
 * Check if a given object implements the ForgotPasswordResponseDto interface.
 */
export function instanceOfForgotPasswordResponseDto(value: object): value is ForgotPasswordResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('temp_token' in value) || value['temp_token'] === undefined) return false;
    return true;
}

export function ForgotPasswordResponseDtoFromJSON(json: any): ForgotPasswordResponseDto {
    return ForgotPasswordResponseDtoFromJSONTyped(json, false);
}

export function ForgotPasswordResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'temp_token': json['temp_token'],
    };
}

export function ForgotPasswordResponseDtoToJSON(value?: ForgotPasswordResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'temp_token': value['temp_token'],
    };
}

