/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponseDto } from './LoginResponseDto';
import {
    LoginResponseDtoFromJSON,
    LoginResponseDtoFromJSONTyped,
    LoginResponseDtoToJSON,
} from './LoginResponseDto';

/**
 * 
 * @export
 * @interface LoginApiResponse
 */
export interface LoginApiResponse {
    /**
     * 
     * @type {number}
     * @memberof LoginApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof LoginApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof LoginApiResponse
     */
    message: string;
    /**
     * 
     * @type {LoginResponseDto}
     * @memberof LoginApiResponse
     */
    data?: LoginResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof LoginApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LoginApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the LoginApiResponse interface.
 */
export function instanceOfLoginApiResponse(value: object): value is LoginApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LoginApiResponseFromJSON(json: any): LoginApiResponse {
    return LoginApiResponseFromJSONTyped(json, false);
}

export function LoginApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : LoginResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function LoginApiResponseToJSON(value?: LoginApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': LoginResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

