/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponseDto } from './UserResponseDto';
import {
    UserResponseDtoFromJSON,
    UserResponseDtoFromJSONTyped,
    UserResponseDtoToJSON,
} from './UserResponseDto';

/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseDto
     */
    is_temp: boolean;
    /**
     * The user
     * @type {UserResponseDto}
     * @memberof LoginResponseDto
     */
    user: UserResponseDto;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    token: string;
}

/**
 * Check if a given object implements the LoginResponseDto interface.
 */
export function instanceOfLoginResponseDto(value: object): value is LoginResponseDto {
    if (!('is_temp' in value) || value['is_temp'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginResponseDtoFromJSON(json: any): LoginResponseDto {
    return LoginResponseDtoFromJSONTyped(json, false);
}

export function LoginResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'is_temp': json['is_temp'],
        'user': UserResponseDtoFromJSON(json['user']),
        'token': json['token'],
    };
}

export function LoginResponseDtoToJSON(value?: LoginResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'is_temp': value['is_temp'],
        'user': UserResponseDtoToJSON(value['user']),
        'token': value['token'],
    };
}

