/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OtpDto
 */
export interface OtpDto {
    /**
     * 
     * @type {number}
     * @memberof OtpDto
     */
    otp: number;
}

/**
 * Check if a given object implements the OtpDto interface.
 */
export function instanceOfOtpDto(value: object): value is OtpDto {
    if (!('otp' in value) || value['otp'] === undefined) return false;
    return true;
}

export function OtpDtoFromJSON(json: any): OtpDto {
    return OtpDtoFromJSONTyped(json, false);
}

export function OtpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtpDto {
    if (json == null) {
        return json;
    }
    return {
        
        'otp': json['otp'],
    };
}

export function OtpDtoToJSON(value?: OtpDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'otp': value['otp'],
    };
}

