/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAnswerDto } from './UserAnswerDto';
import {
    UserAnswerDtoFromJSON,
    UserAnswerDtoFromJSONTyped,
    UserAnswerDtoToJSON,
} from './UserAnswerDto';

/**
 * 
 * @export
 * @interface QuestionWithAnswersDto
 */
export interface QuestionWithAnswersDto {
    /**
     * Question ID
     * @type {string}
     * @memberof QuestionWithAnswersDto
     */
    id: string;
    /**
     * Question text
     * @type {string}
     * @memberof QuestionWithAnswersDto
     */
    question_text: string;
    /**
     * Question type
     * @type {string}
     * @memberof QuestionWithAnswersDto
     */
    question_type: QuestionWithAnswersDtoQuestionTypeEnum;
    /**
     * Question options (for MCQ questions)
     * @type {Array<string>}
     * @memberof QuestionWithAnswersDto
     */
    options: Array<string> | null;
    /**
     * Difficulty level
     * @type {string}
     * @memberof QuestionWithAnswersDto
     */
    difficulty: QuestionWithAnswersDtoDifficultyEnum;
    /**
     * Question order sequence
     * @type {number}
     * @memberof QuestionWithAnswersDto
     */
    order_sequence: number;
    /**
     * User answers
     * @type {UserAnswerDto}
     * @memberof QuestionWithAnswersDto
     */
    user_answers?: UserAnswerDto | null;
    /**
     * Correct answer
     * @type {string}
     * @memberof QuestionWithAnswersDto
     */
    correct_answer?: string;
}


/**
 * @export
 */
export const QuestionWithAnswersDtoQuestionTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type QuestionWithAnswersDtoQuestionTypeEnum = typeof QuestionWithAnswersDtoQuestionTypeEnum[keyof typeof QuestionWithAnswersDtoQuestionTypeEnum];

/**
 * @export
 */
export const QuestionWithAnswersDtoDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type QuestionWithAnswersDtoDifficultyEnum = typeof QuestionWithAnswersDtoDifficultyEnum[keyof typeof QuestionWithAnswersDtoDifficultyEnum];


/**
 * Check if a given object implements the QuestionWithAnswersDto interface.
 */
export function instanceOfQuestionWithAnswersDto(value: object): value is QuestionWithAnswersDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('question_text' in value) || value['question_text'] === undefined) return false;
    if (!('question_type' in value) || value['question_type'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('order_sequence' in value) || value['order_sequence'] === undefined) return false;
    return true;
}

export function QuestionWithAnswersDtoFromJSON(json: any): QuestionWithAnswersDto {
    return QuestionWithAnswersDtoFromJSONTyped(json, false);
}

export function QuestionWithAnswersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionWithAnswersDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'question_text': json['question_text'],
        'question_type': json['question_type'],
        'options': json['options'],
        'difficulty': json['difficulty'],
        'order_sequence': json['order_sequence'],
        'user_answers': json['user_answers'] == null ? undefined : UserAnswerDtoFromJSON(json['user_answers']),
        'correct_answer': json['correct_answer'] == null ? undefined : json['correct_answer'],
    };
}

export function QuestionWithAnswersDtoToJSON(value?: QuestionWithAnswersDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'question_text': value['question_text'],
        'question_type': value['question_type'],
        'options': value['options'],
        'difficulty': value['difficulty'],
        'order_sequence': value['order_sequence'],
        'user_answers': UserAnswerDtoToJSON(value['user_answers']),
        'correct_answer': value['correct_answer'],
    };
}

