/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResetPasswordResponseDto } from './ResetPasswordResponseDto';
import {
    ResetPasswordResponseDtoFromJSON,
    ResetPasswordResponseDtoFromJSONTyped,
    ResetPasswordResponseDtoToJSON,
} from './ResetPasswordResponseDto';

/**
 * 
 * @export
 * @interface ResetPasswordApiResponse
 */
export interface ResetPasswordApiResponse {
    /**
     * 
     * @type {number}
     * @memberof ResetPasswordApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordApiResponse
     */
    message: string;
    /**
     * 
     * @type {ResetPasswordResponseDto}
     * @memberof ResetPasswordApiResponse
     */
    data?: ResetPasswordResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof ResetPasswordApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the ResetPasswordApiResponse interface.
 */
export function instanceOfResetPasswordApiResponse(value: object): value is ResetPasswordApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ResetPasswordApiResponseFromJSON(json: any): ResetPasswordApiResponse {
    return ResetPasswordApiResponseFromJSONTyped(json, false);
}

export function ResetPasswordApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : ResetPasswordResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ResetPasswordApiResponseToJSON(value?: ResetPasswordApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': ResetPasswordResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

