/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordResponseDto
 */
export interface ResetPasswordResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the ResetPasswordResponseDto interface.
 */
export function instanceOfResetPasswordResponseDto(value: object): value is ResetPasswordResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ResetPasswordResponseDtoFromJSON(json: any): ResetPasswordResponseDto {
    return ResetPasswordResponseDtoFromJSONTyped(json, false);
}

export function ResetPasswordResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ResetPasswordResponseDtoToJSON(value?: ResetPasswordResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

