/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAssessmentResponseDto } from './UserAssessmentResponseDto';
import {
    UserAssessmentResponseDtoFromJSON,
    UserAssessmentResponseDtoFromJSONTyped,
    UserAssessmentResponseDtoToJSON,
} from './UserAssessmentResponseDto';

/**
 * 
 * @export
 * @interface StartAssessmentApiResponse
 */
export interface StartAssessmentApiResponse {
    /**
     * 
     * @type {number}
     * @memberof StartAssessmentApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof StartAssessmentApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof StartAssessmentApiResponse
     */
    message: string;
    /**
     * 
     * @type {UserAssessmentResponseDto}
     * @memberof StartAssessmentApiResponse
     */
    data?: UserAssessmentResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof StartAssessmentApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof StartAssessmentApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the StartAssessmentApiResponse interface.
 */
export function instanceOfStartAssessmentApiResponse(value: object): value is StartAssessmentApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function StartAssessmentApiResponseFromJSON(json: any): StartAssessmentApiResponse {
    return StartAssessmentApiResponseFromJSONTyped(json, false);
}

export function StartAssessmentApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAssessmentApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserAssessmentResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function StartAssessmentApiResponseToJSON(value?: StartAssessmentApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserAssessmentResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

