/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartAssessmentBodyDto
 */
export interface StartAssessmentBodyDto {
    /**
     * Assessment ID (required when userAssessmentId is not provided)
     * @type {string}
     * @memberof StartAssessmentBodyDto
     */
    assessmentId?: string;
}

/**
 * Check if a given object implements the StartAssessmentBodyDto interface.
 */
export function instanceOfStartAssessmentBodyDto(value: object): value is StartAssessmentBodyDto {
    return true;
}

export function StartAssessmentBodyDtoFromJSON(json: any): StartAssessmentBodyDto {
    return StartAssessmentBodyDtoFromJSONTyped(json, false);
}

export function StartAssessmentBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAssessmentBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'assessmentId': json['assessmentId'] == null ? undefined : json['assessmentId'],
    };
}

export function StartAssessmentBodyDtoToJSON(value?: StartAssessmentBodyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assessmentId': value['assessmentId'],
    };
}

