/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreAnswerDto
 */
export interface StoreAnswerDto {
    /**
     * The answer to the question
     * @type {string}
     * @memberof StoreAnswerDto
     */
    answer: string;
}

/**
 * Check if a given object implements the StoreAnswerDto interface.
 */
export function instanceOfStoreAnswerDto(value: object): value is StoreAnswerDto {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function StoreAnswerDtoFromJSON(json: any): StoreAnswerDto {
    return StoreAnswerDtoFromJSONTyped(json, false);
}

export function StoreAnswerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreAnswerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
    };
}

export function StoreAnswerDtoToJSON(value?: StoreAnswerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'answer': value['answer'],
    };
}

