/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserProfileDto
 */
export interface UpdateUserProfileDto {
    /**
     * User full name
     * @type {string}
     * @memberof UpdateUserProfileDto
     */
    full_name?: string;
    /**
     * User gender
     * @type {string}
     * @memberof UpdateUserProfileDto
     */
    gender?: UpdateUserProfileDtoGenderEnum;
    /**
     * Date of birth (YYYY-MM-DD)
     * @type {string}
     * @memberof UpdateUserProfileDto
     */
    date_of_birth?: string;
    /**
     * Array of course IDs to enroll in
     * @type {Array<string>}
     * @memberof UpdateUserProfileDto
     */
    enrolled_courses?: Array<string>;
}


/**
 * @export
 */
export const UpdateUserProfileDtoGenderEnum = {
    Male: 'male',
    Female: 'female',
    Other: 'other',
    PreferNotToSay: 'prefer_not_to_say'
} as const;
export type UpdateUserProfileDtoGenderEnum = typeof UpdateUserProfileDtoGenderEnum[keyof typeof UpdateUserProfileDtoGenderEnum];


/**
 * Check if a given object implements the UpdateUserProfileDto interface.
 */
export function instanceOfUpdateUserProfileDto(value: object): value is UpdateUserProfileDto {
    return true;
}

export function UpdateUserProfileDtoFromJSON(json: any): UpdateUserProfileDto {
    return UpdateUserProfileDtoFromJSONTyped(json, false);
}

export function UpdateUserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'full_name': json['full_name'] == null ? undefined : json['full_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'enrolled_courses': json['enrolled_courses'] == null ? undefined : json['enrolled_courses'],
    };
}

export function UpdateUserProfileDtoToJSON(value?: UpdateUserProfileDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'full_name': value['full_name'],
        'gender': value['gender'],
        'date_of_birth': value['date_of_birth'],
        'enrolled_courses': value['enrolled_courses'],
    };
}

