/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpsertQuestionDto } from './UpsertQuestionDto';
import {
    UpsertQuestionDtoFromJSON,
    UpsertQuestionDtoFromJSONTyped,
    UpsertQuestionDtoToJSON,
} from './UpsertQuestionDto';

/**
 * 
 * @export
 * @interface UpsertAssessmentDto
 */
export interface UpsertAssessmentDto {
    /**
     * Assessment ID (for updates, omit for new assessments)
     * @type {string}
     * @memberof UpsertAssessmentDto
     */
    id?: string;
    /**
     * Course ID
     * @type {string}
     * @memberof UpsertAssessmentDto
     */
    course_id?: string;
    /**
     * Assessment name
     * @type {string}
     * @memberof UpsertAssessmentDto
     */
    name: string;
    /**
     * Assessment type
     * @type {string}
     * @memberof UpsertAssessmentDto
     */
    type: UpsertAssessmentDtoTypeEnum;
    /**
     * Assessment difficulty level
     * @type {string}
     * @memberof UpsertAssessmentDto
     */
    difficulty: UpsertAssessmentDtoDifficultyEnum;
    /**
     * Duration in minutes
     * @type {number}
     * @memberof UpsertAssessmentDto
     */
    duration_minutes?: number;
    /**
     * Assessment description
     * @type {string}
     * @memberof UpsertAssessmentDto
     */
    description?: string;
    /**
     * Maximum score
     * @type {number}
     * @memberof UpsertAssessmentDto
     */
    max_score: number;
    /**
     * Maximum number of questions
     * @type {number}
     * @memberof UpsertAssessmentDto
     */
    max_questions: number;
    /**
     * Array of questions for the assessment
     * @type {Array<UpsertQuestionDto>}
     * @memberof UpsertAssessmentDto
     */
    questions: Array<UpsertQuestionDto>;
}


/**
 * @export
 */
export const UpsertAssessmentDtoTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type UpsertAssessmentDtoTypeEnum = typeof UpsertAssessmentDtoTypeEnum[keyof typeof UpsertAssessmentDtoTypeEnum];

/**
 * @export
 */
export const UpsertAssessmentDtoDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type UpsertAssessmentDtoDifficultyEnum = typeof UpsertAssessmentDtoDifficultyEnum[keyof typeof UpsertAssessmentDtoDifficultyEnum];


/**
 * Check if a given object implements the UpsertAssessmentDto interface.
 */
export function instanceOfUpsertAssessmentDto(value: object): value is UpsertAssessmentDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('max_score' in value) || value['max_score'] === undefined) return false;
    if (!('max_questions' in value) || value['max_questions'] === undefined) return false;
    if (!('questions' in value) || value['questions'] === undefined) return false;
    return true;
}

export function UpsertAssessmentDtoFromJSON(json: any): UpsertAssessmentDto {
    return UpsertAssessmentDtoFromJSONTyped(json, false);
}

export function UpsertAssessmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertAssessmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'course_id': json['course_id'] == null ? undefined : json['course_id'],
        'name': json['name'],
        'type': json['type'],
        'difficulty': json['difficulty'],
        'duration_minutes': json['duration_minutes'] == null ? undefined : json['duration_minutes'],
        'description': json['description'] == null ? undefined : json['description'],
        'max_score': json['max_score'],
        'max_questions': json['max_questions'],
        'questions': ((json['questions'] as Array<any>).map(UpsertQuestionDtoFromJSON)),
    };
}

export function UpsertAssessmentDtoToJSON(value?: UpsertAssessmentDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'course_id': value['course_id'],
        'name': value['name'],
        'type': value['type'],
        'difficulty': value['difficulty'],
        'duration_minutes': value['duration_minutes'],
        'description': value['description'],
        'max_score': value['max_score'],
        'max_questions': value['max_questions'],
        'questions': ((value['questions'] as Array<any>).map(UpsertQuestionDtoToJSON)),
    };
}

