/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertQuestionDto
 */
export interface UpsertQuestionDto {
    /**
     * Question ID (for updates, omit for new questions)
     * @type {string}
     * @memberof UpsertQuestionDto
     */
    id?: string;
    /**
     * Question text
     * @type {string}
     * @memberof UpsertQuestionDto
     */
    question_text: string;
    /**
     * Question type
     * @type {string}
     * @memberof UpsertQuestionDto
     */
    question_type: UpsertQuestionDtoQuestionTypeEnum;
    /**
     * Question options (required for MCQ questions)
     * @type {Array<string>}
     * @memberof UpsertQuestionDto
     */
    options?: Array<string>;
    /**
     * Correct answer (required for MCQ questions)
     * @type {string}
     * @memberof UpsertQuestionDto
     */
    correct_answer?: string;
    /**
     * Question difficulty level
     * @type {string}
     * @memberof UpsertQuestionDto
     */
    difficulty: UpsertQuestionDtoDifficultyEnum;
    /**
     * Question order sequence
     * @type {number}
     * @memberof UpsertQuestionDto
     */
    order_sequence: number;
}


/**
 * @export
 */
export const UpsertQuestionDtoQuestionTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type UpsertQuestionDtoQuestionTypeEnum = typeof UpsertQuestionDtoQuestionTypeEnum[keyof typeof UpsertQuestionDtoQuestionTypeEnum];

/**
 * @export
 */
export const UpsertQuestionDtoDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type UpsertQuestionDtoDifficultyEnum = typeof UpsertQuestionDtoDifficultyEnum[keyof typeof UpsertQuestionDtoDifficultyEnum];


/**
 * Check if a given object implements the UpsertQuestionDto interface.
 */
export function instanceOfUpsertQuestionDto(value: object): value is UpsertQuestionDto {
    if (!('question_text' in value) || value['question_text'] === undefined) return false;
    if (!('question_type' in value) || value['question_type'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('order_sequence' in value) || value['order_sequence'] === undefined) return false;
    return true;
}

export function UpsertQuestionDtoFromJSON(json: any): UpsertQuestionDto {
    return UpsertQuestionDtoFromJSONTyped(json, false);
}

export function UpsertQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'question_text': json['question_text'],
        'question_type': json['question_type'],
        'options': json['options'] == null ? undefined : json['options'],
        'correct_answer': json['correct_answer'] == null ? undefined : json['correct_answer'],
        'difficulty': json['difficulty'],
        'order_sequence': json['order_sequence'],
    };
}

export function UpsertQuestionDtoToJSON(value?: UpsertQuestionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'question_text': value['question_text'],
        'question_type': value['question_type'],
        'options': value['options'],
        'correct_answer': value['correct_answer'],
        'difficulty': value['difficulty'],
        'order_sequence': value['order_sequence'],
    };
}

