/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertQuestionResponseDto
 */
export interface UpsertQuestionResponseDto {
    /**
     * Question ID
     * @type {string}
     * @memberof UpsertQuestionResponseDto
     */
    id: string;
    /**
     * Question text
     * @type {string}
     * @memberof UpsertQuestionResponseDto
     */
    question_text: string;
    /**
     * Question type
     * @type {string}
     * @memberof UpsertQuestionResponseDto
     */
    question_type: UpsertQuestionResponseDtoQuestionTypeEnum;
    /**
     * Question options
     * @type {Array<string>}
     * @memberof UpsertQuestionResponseDto
     */
    options?: Array<string>;
    /**
     * Correct answer
     * @type {string}
     * @memberof UpsertQuestionResponseDto
     */
    correct_answer?: string;
    /**
     * Question difficulty level
     * @type {string}
     * @memberof UpsertQuestionResponseDto
     */
    difficulty: UpsertQuestionResponseDtoDifficultyEnum;
    /**
     * Question order sequence
     * @type {number}
     * @memberof UpsertQuestionResponseDto
     */
    order_sequence: number;
}


/**
 * @export
 */
export const UpsertQuestionResponseDtoQuestionTypeEnum = {
    Mcq: 'mcq',
    Subjective: 'subjective'
} as const;
export type UpsertQuestionResponseDtoQuestionTypeEnum = typeof UpsertQuestionResponseDtoQuestionTypeEnum[keyof typeof UpsertQuestionResponseDtoQuestionTypeEnum];

/**
 * @export
 */
export const UpsertQuestionResponseDtoDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type UpsertQuestionResponseDtoDifficultyEnum = typeof UpsertQuestionResponseDtoDifficultyEnum[keyof typeof UpsertQuestionResponseDtoDifficultyEnum];


/**
 * Check if a given object implements the UpsertQuestionResponseDto interface.
 */
export function instanceOfUpsertQuestionResponseDto(value: object): value is UpsertQuestionResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('question_text' in value) || value['question_text'] === undefined) return false;
    if (!('question_type' in value) || value['question_type'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('order_sequence' in value) || value['order_sequence'] === undefined) return false;
    return true;
}

export function UpsertQuestionResponseDtoFromJSON(json: any): UpsertQuestionResponseDto {
    return UpsertQuestionResponseDtoFromJSONTyped(json, false);
}

export function UpsertQuestionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertQuestionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'question_text': json['question_text'],
        'question_type': json['question_type'],
        'options': json['options'] == null ? undefined : json['options'],
        'correct_answer': json['correct_answer'] == null ? undefined : json['correct_answer'],
        'difficulty': json['difficulty'],
        'order_sequence': json['order_sequence'],
    };
}

export function UpsertQuestionResponseDtoToJSON(value?: UpsertQuestionResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'question_text': value['question_text'],
        'question_type': value['question_type'],
        'options': value['options'],
        'correct_answer': value['correct_answer'],
        'difficulty': value['difficulty'],
        'order_sequence': value['order_sequence'],
    };
}

