/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpsertAssessmentResponseDto } from './UpsertAssessmentResponseDto';
import {
    UpsertAssessmentResponseDtoFromJSON,
    UpsertAssessmentResponseDtoFromJSONTyped,
    UpsertAssessmentResponseDtoToJSON,
} from './UpsertAssessmentResponseDto';

/**
 * 
 * @export
 * @interface UpsertAssessmentApiResponse
 */
export interface UpsertAssessmentApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UpsertAssessmentApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UpsertAssessmentApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertAssessmentApiResponse
     */
    message: string;
    /**
     * Upserted assessment data
     * @type {UpsertAssessmentResponseDto}
     * @memberof UpsertAssessmentApiResponse
     */
    data?: UpsertAssessmentResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertAssessmentApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UpsertAssessmentApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UpsertAssessmentApiResponse interface.
 */
export function instanceOfUpsertAssessmentApiResponse(value: object): value is UpsertAssessmentApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UpsertAssessmentApiResponseFromJSON(json: any): UpsertAssessmentApiResponse {
    return UpsertAssessmentApiResponseFromJSONTyped(json, false);
}

export function UpsertAssessmentApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertAssessmentApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UpsertAssessmentResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UpsertAssessmentApiResponseToJSON(value?: UpsertAssessmentApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UpsertAssessmentResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

