/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAnalyticsResponseDto } from './UserAnalyticsResponseDto';
import {
    UserAnalyticsResponseDtoFromJSON,
    UserAnalyticsResponseDtoFromJSONTyped,
    UserAnalyticsResponseDtoToJSON,
} from './UserAnalyticsResponseDto';

/**
 * 
 * @export
 * @interface UserAnalyticsApiResponse
 */
export interface UserAnalyticsApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserAnalyticsApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UserAnalyticsApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserAnalyticsApiResponse
     */
    message: string;
    /**
     * User analytics response data
     * @type {UserAnalyticsResponseDto}
     * @memberof UserAnalyticsApiResponse
     */
    data?: UserAnalyticsResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UserAnalyticsApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserAnalyticsApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UserAnalyticsApiResponse interface.
 */
export function instanceOfUserAnalyticsApiResponse(value: object): value is UserAnalyticsApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UserAnalyticsApiResponseFromJSON(json: any): UserAnalyticsApiResponse {
    return UserAnalyticsApiResponseFromJSONTyped(json, false);
}

export function UserAnalyticsApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAnalyticsApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserAnalyticsResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UserAnalyticsApiResponseToJSON(value?: UserAnalyticsApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserAnalyticsResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

