/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationDetailsDto } from './PaginationDetailsDto';
import {
    PaginationDetailsDtoFromJSON,
    PaginationDetailsDtoFromJSONTyped,
    PaginationDetailsDtoToJSON,
} from './PaginationDetailsDto';
import type { UserAssessmentItemDto } from './UserAssessmentItemDto';
import {
    UserAssessmentItemDtoFromJSON,
    UserAssessmentItemDtoFromJSONTyped,
    UserAssessmentItemDtoToJSON,
} from './UserAssessmentItemDto';

/**
 * 
 * @export
 * @interface UserAssessmentListResponseDto
 */
export interface UserAssessmentListResponseDto {
    /**
     * List of user assessments
     * @type {Array<UserAssessmentItemDto>}
     * @memberof UserAssessmentListResponseDto
     */
    assessments: Array<UserAssessmentItemDto>;
    /**
     * Pagination details
     * @type {PaginationDetailsDto}
     * @memberof UserAssessmentListResponseDto
     */
    pagination: PaginationDetailsDto;
}

/**
 * Check if a given object implements the UserAssessmentListResponseDto interface.
 */
export function instanceOfUserAssessmentListResponseDto(value: object): value is UserAssessmentListResponseDto {
    if (!('assessments' in value) || value['assessments'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function UserAssessmentListResponseDtoFromJSON(json: any): UserAssessmentListResponseDto {
    return UserAssessmentListResponseDtoFromJSONTyped(json, false);
}

export function UserAssessmentListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAssessmentListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'assessments': ((json['assessments'] as Array<any>).map(UserAssessmentItemDtoFromJSON)),
        'pagination': PaginationDetailsDtoFromJSON(json['pagination']),
    };
}

export function UserAssessmentListResponseDtoToJSON(value?: UserAssessmentListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assessments': ((value['assessments'] as Array<any>).map(UserAssessmentItemDtoToJSON)),
        'pagination': PaginationDetailsDtoToJSON(value['pagination']),
    };
}

