/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRankingDto
 */
export interface UserRankingDto {
    /**
     * Analytics record ID
     * @type {string}
     * @memberof UserRankingDto
     */
    id: string;
    /**
     * User ID
     * @type {string}
     * @memberof UserRankingDto
     */
    user_id: string;
    /**
     * User full name
     * @type {string}
     * @memberof UserRankingDto
     */
    full_name?: string | null;
    /**
     * User email
     * @type {string}
     * @memberof UserRankingDto
     */
    email: string;
    /**
     * User avatar URL
     * @type {string}
     * @memberof UserRankingDto
     */
    avatar?: string | null;
    /**
     * Average score percentage
     * @type {number}
     * @memberof UserRankingDto
     */
    average_score?: number | null;
    /**
     * Last test taken timestamp
     * @type {Date}
     * @memberof UserRankingDto
     */
    test_taken_at?: Date | null;
    /**
     * User rank based on average score
     * @type {number}
     * @memberof UserRankingDto
     */
    rank?: number | null;
    /**
     * Number of assessments given
     * @type {number}
     * @memberof UserRankingDto
     */
    given_assessments?: number | null;
    /**
     * Number of upcoming assessments
     * @type {number}
     * @memberof UserRankingDto
     */
    upcoming_assessments?: number | null;
}

/**
 * Check if a given object implements the UserRankingDto interface.
 */
export function instanceOfUserRankingDto(value: object): value is UserRankingDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserRankingDtoFromJSON(json: any): UserRankingDto {
    return UserRankingDtoFromJSONTyped(json, false);
}

export function UserRankingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRankingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'full_name': json['full_name'] == null ? undefined : json['full_name'],
        'email': json['email'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'average_score': json['average_score'] == null ? undefined : json['average_score'],
        'test_taken_at': json['test_taken_at'] == null ? undefined : (new Date(json['test_taken_at'])),
        'rank': json['rank'] == null ? undefined : json['rank'],
        'given_assessments': json['given_assessments'] == null ? undefined : json['given_assessments'],
        'upcoming_assessments': json['upcoming_assessments'] == null ? undefined : json['upcoming_assessments'],
    };
}

export function UserRankingDtoToJSON(value?: UserRankingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'full_name': value['full_name'],
        'email': value['email'],
        'avatar': value['avatar'],
        'average_score': value['average_score'],
        'test_taken_at': value['test_taken_at'] == null ? undefined : ((value['test_taken_at'] as any).toISOString()),
        'rank': value['rank'],
        'given_assessments': value['given_assessments'],
        'upcoming_assessments': value['upcoming_assessments'],
    };
}

