/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAnswerDto
 */
export interface UserAnswerDto {
    /**
     * User answer ID
     * @type {string}
     * @memberof UserAnswerDto
     */
    id: string;
    /**
     * User answer
     * @type {string}
     * @memberof UserAnswerDto
     */
    answer: string;
    /**
     * Is the answer correct
     * @type {boolean}
     * @memberof UserAnswerDto
     */
    is_correct: boolean;
    /**
     * Points earned
     * @type {number}
     * @memberof UserAnswerDto
     */
    points_earned: number;
}

/**
 * Check if a given object implements the UserAnswerDto interface.
 */
export function instanceOfUserAnswerDto(value: object): value is UserAnswerDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('is_correct' in value) || value['is_correct'] === undefined) return false;
    if (!('points_earned' in value) || value['points_earned'] === undefined) return false;
    return true;
}

export function UserAnswerDtoFromJSON(json: any): UserAnswerDto {
    return UserAnswerDtoFromJSONTyped(json, false);
}

export function UserAnswerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAnswerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'answer': json['answer'],
        'is_correct': json['is_correct'],
        'points_earned': json['points_earned'],
    };
}

export function UserAnswerDtoToJSON(value?: UserAnswerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'answer': value['answer'],
        'is_correct': value['is_correct'],
        'points_earned': value['points_earned'],
    };
}

