/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunityAnalyticsDto } from './CommunityAnalyticsDto';
import {
    CommunityAnalyticsDtoFromJSON,
    CommunityAnalyticsDtoFromJSONTyped,
    CommunityAnalyticsDtoToJSON,
} from './CommunityAnalyticsDto';
import type { UserRankingDto } from './UserRankingDto';
import {
    UserRankingDtoFromJSON,
    UserRankingDtoFromJSONTyped,
    UserRankingDtoToJSON,
} from './UserRankingDto';

/**
 * 
 * @export
 * @interface UserRankingResponseDto
 */
export interface UserRankingResponseDto {
    /**
     * User ranking data
     * @type {Array<UserRankingDto>}
     * @memberof UserRankingResponseDto
     */
    rankings: Array<UserRankingDto>;
    /**
     * Community analytics data
     * @type {CommunityAnalyticsDto}
     * @memberof UserRankingResponseDto
     */
    communityAnalytics: CommunityAnalyticsDto;
}

/**
 * Check if a given object implements the UserRankingResponseDto interface.
 */
export function instanceOfUserRankingResponseDto(value: object): value is UserRankingResponseDto {
    if (!('rankings' in value) || value['rankings'] === undefined) return false;
    if (!('communityAnalytics' in value) || value['communityAnalytics'] === undefined) return false;
    return true;
}

export function UserRankingResponseDtoFromJSON(json: any): UserRankingResponseDto {
    return UserRankingResponseDtoFromJSONTyped(json, false);
}

export function UserRankingResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRankingResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rankings': ((json['rankings'] as Array<any>).map(UserRankingDtoFromJSON)),
        'communityAnalytics': CommunityAnalyticsDtoFromJSON(json['communityAnalytics']),
    };
}

export function UserRankingResponseDtoToJSON(value?: UserRankingResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rankings': ((value['rankings'] as Array<any>).map(UserRankingDtoToJSON)),
        'communityAnalytics': CommunityAnalyticsDtoToJSON(value['communityAnalytics']),
    };
}

