/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserListResponseDto } from './UserListResponseDto';
import {
    UserListResponseDtoFromJSON,
    UserListResponseDtoFromJSONTyped,
    UserListResponseDtoToJSON,
} from './UserListResponseDto';

/**
 * 
 * @export
 * @interface UserListApiResponse
 */
export interface UserListApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserListApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UserListApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserListApiResponse
     */
    message: string;
    /**
     * User list response data
     * @type {UserListResponseDto}
     * @memberof UserListApiResponse
     */
    data?: UserListResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UserListApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserListApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UserListApiResponse interface.
 */
export function instanceOfUserListApiResponse(value: object): value is UserListApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UserListApiResponseFromJSON(json: any): UserListApiResponse {
    return UserListApiResponseFromJSONTyped(json, false);
}

export function UserListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserListResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UserListApiResponseToJSON(value?: UserListApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserListResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

