/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponseDto } from './UserResponseDto';
import {
    UserResponseDtoFromJSON,
    UserResponseDtoFromJSONTyped,
    UserResponseDtoToJSON,
} from './UserResponseDto';

/**
 * 
 * @export
 * @interface UserResponseApiResponse
 */
export interface UserResponseApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserResponseApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseApiResponse
     */
    message: string;
    /**
     * 
     * @type {UserResponseDto}
     * @memberof UserResponseApiResponse
     */
    data?: UserResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserResponseApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UserResponseApiResponse interface.
 */
export function instanceOfUserResponseApiResponse(value: object): value is UserResponseApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UserResponseApiResponseFromJSON(json: any): UserResponseApiResponse {
    return UserResponseApiResponseFromJSONTyped(json, false);
}

export function UserResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UserResponseApiResponseToJSON(value?: UserResponseApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

