/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRankingResponseDto } from './UserRankingResponseDto';
import {
    UserRankingResponseDtoFromJSON,
    UserRankingResponseDtoFromJSONTyped,
    UserRankingResponseDtoToJSON,
} from './UserRankingResponseDto';

/**
 * 
 * @export
 * @interface UserRankingApiResponse
 */
export interface UserRankingApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserRankingApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UserRankingApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserRankingApiResponse
     */
    message: string;
    /**
     * User ranking response data
     * @type {UserRankingResponseDto}
     * @memberof UserRankingApiResponse
     */
    data?: UserRankingResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UserRankingApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserRankingApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UserRankingApiResponse interface.
 */
export function instanceOfUserRankingApiResponse(value: object): value is UserRankingApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UserRankingApiResponseFromJSON(json: any): UserRankingApiResponse {
    return UserRankingApiResponseFromJSONTyped(json, false);
}

export function UserRankingApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRankingApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserRankingResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UserRankingApiResponseToJSON(value?: UserRankingApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserRankingResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

