/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseDto } from './CourseDto';
import {
    CourseDtoFromJSON,
    CourseDtoFromJSONTyped,
    CourseDtoToJSON,
} from './CourseDto';

/**
 * 
 * @export
 * @interface UserProfileDto
 */
export interface UserProfileDto {
    /**
     * User ID
     * @type {string}
     * @memberof UserProfileDto
     */
    id: string;
    /**
     * User full name
     * @type {string}
     * @memberof UserProfileDto
     */
    full_name?: string;
    /**
     * User email
     * @type {string}
     * @memberof UserProfileDto
     */
    email: string;
    /**
     * User avatar URL
     * @type {string}
     * @memberof UserProfileDto
     */
    avatar?: string;
    /**
     * User phone number
     * @type {string}
     * @memberof UserProfileDto
     */
    phone_number?: string;
    /**
     * Country code
     * @type {string}
     * @memberof UserProfileDto
     */
    country_code?: string;
    /**
     * User gender
     * @type {string}
     * @memberof UserProfileDto
     */
    gender?: UserProfileDtoGenderEnum;
    /**
     * Date of birth
     * @type {string}
     * @memberof UserProfileDto
     */
    date_of_birth?: string;
    /**
     * Whether email is verified
     * @type {boolean}
     * @memberof UserProfileDto
     */
    is_email_verified: boolean;
    /**
     * Whether phone is verified
     * @type {boolean}
     * @memberof UserProfileDto
     */
    is_phone_verified: boolean;
    /**
     * User enrolled courses
     * @type {Array<CourseDto>}
     * @memberof UserProfileDto
     */
    enrolled_courses?: Array<CourseDto>;
    /**
     * Account creation date
     * @type {string}
     * @memberof UserProfileDto
     */
    created_at: string;
}


/**
 * @export
 */
export const UserProfileDtoGenderEnum = {
    Male: 'male',
    Female: 'female',
    Other: 'other',
    PreferNotToSay: 'prefer_not_to_say'
} as const;
export type UserProfileDtoGenderEnum = typeof UserProfileDtoGenderEnum[keyof typeof UserProfileDtoGenderEnum];


/**
 * Check if a given object implements the UserProfileDto interface.
 */
export function instanceOfUserProfileDto(value: object): value is UserProfileDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('is_email_verified' in value) || value['is_email_verified'] === undefined) return false;
    if (!('is_phone_verified' in value) || value['is_phone_verified'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function UserProfileDtoFromJSON(json: any): UserProfileDto {
    return UserProfileDtoFromJSONTyped(json, false);
}

export function UserProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'full_name': json['full_name'] == null ? undefined : json['full_name'],
        'email': json['email'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
        'country_code': json['country_code'] == null ? undefined : json['country_code'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'date_of_birth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'is_email_verified': json['is_email_verified'],
        'is_phone_verified': json['is_phone_verified'],
        'enrolled_courses': json['enrolled_courses'] == null ? undefined : ((json['enrolled_courses'] as Array<any>).map(CourseDtoFromJSON)),
        'created_at': json['created_at'],
    };
}

export function UserProfileDtoToJSON(value?: UserProfileDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'full_name': value['full_name'],
        'email': value['email'],
        'avatar': value['avatar'],
        'phone_number': value['phone_number'],
        'country_code': value['country_code'],
        'gender': value['gender'],
        'date_of_birth': value['date_of_birth'],
        'is_email_verified': value['is_email_verified'],
        'is_phone_verified': value['is_phone_verified'],
        'enrolled_courses': value['enrolled_courses'] == null ? undefined : ((value['enrolled_courses'] as Array<any>).map(CourseDtoToJSON)),
        'created_at': value['created_at'],
    };
}

