/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileResponseDto } from './UserProfileResponseDto';
import {
    UserProfileResponseDtoFromJSON,
    UserProfileResponseDtoFromJSONTyped,
    UserProfileResponseDtoToJSON,
} from './UserProfileResponseDto';

/**
 * 
 * @export
 * @interface UserProfileApiResponse
 */
export interface UserProfileApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserProfileApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileApiResponse
     */
    message: string;
    /**
     * 
     * @type {UserProfileResponseDto}
     * @memberof UserProfileApiResponse
     */
    data?: UserProfileResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserProfileApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UserProfileApiResponse interface.
 */
export function instanceOfUserProfileApiResponse(value: object): value is UserProfileApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UserProfileApiResponseFromJSON(json: any): UserProfileApiResponse {
    return UserProfileApiResponseFromJSONTyped(json, false);
}

export function UserProfileApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserProfileResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UserProfileApiResponseToJSON(value?: UserProfileApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserProfileResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

