/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserIdDto
 */
export interface UserIdDto {
    /**
     * User ID
     * @type {string}
     * @memberof UserIdDto
     */
    user_id: string;
}

/**
 * Check if a given object implements the UserIdDto interface.
 */
export function instanceOfUserIdDto(value: object): value is UserIdDto {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function UserIdDtoFromJSON(json: any): UserIdDto {
    return UserIdDtoFromJSONTyped(json, false);
}

export function UserIdDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdDto {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
    };
}

export function UserIdDtoToJSON(value?: UserIdDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_id': value['user_id'],
    };
}

