/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAssessmentListResponseDto } from './UserAssessmentListResponseDto';
import {
    UserAssessmentListResponseDtoFromJSON,
    UserAssessmentListResponseDtoFromJSONTyped,
    UserAssessmentListResponseDtoToJSON,
} from './UserAssessmentListResponseDto';

/**
 * 
 * @export
 * @interface UserAssessmentListApiResponse
 */
export interface UserAssessmentListApiResponse {
    /**
     * 
     * @type {number}
     * @memberof UserAssessmentListApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof UserAssessmentListApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof UserAssessmentListApiResponse
     */
    message: string;
    /**
     * User assessment list data
     * @type {UserAssessmentListResponseDto}
     * @memberof UserAssessmentListApiResponse
     */
    data?: UserAssessmentListResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof UserAssessmentListApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserAssessmentListApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the UserAssessmentListApiResponse interface.
 */
export function instanceOfUserAssessmentListApiResponse(value: object): value is UserAssessmentListApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UserAssessmentListApiResponseFromJSON(json: any): UserAssessmentListApiResponse {
    return UserAssessmentListApiResponseFromJSONTyped(json, false);
}

export function UserAssessmentListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAssessmentListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : UserAssessmentListResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function UserAssessmentListApiResponseToJSON(value?: UserAssessmentListApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': UserAssessmentListResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

