/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAnalyticsDto
 */
export interface UserAnalyticsDto {
    /**
     * Last test taken timestamp
     * @type {Date}
     * @memberof UserAnalyticsDto
     */
    test_taken_at?: Date | null;
    /**
     * Average score percentage
     * @type {number}
     * @memberof UserAnalyticsDto
     */
    average_score?: number | null;
    /**
     * User rank based on average score
     * @type {number}
     * @memberof UserAnalyticsDto
     */
    rank?: number | null;
    /**
     * Number of assessments given
     * @type {number}
     * @memberof UserAnalyticsDto
     */
    given_assessments?: number | null;
    /**
     * Number of upcoming assessments
     * @type {number}
     * @memberof UserAnalyticsDto
     */
    upcoming_assessments?: number | null;
}

/**
 * Check if a given object implements the UserAnalyticsDto interface.
 */
export function instanceOfUserAnalyticsDto(value: object): value is UserAnalyticsDto {
    return true;
}

export function UserAnalyticsDtoFromJSON(json: any): UserAnalyticsDto {
    return UserAnalyticsDtoFromJSONTyped(json, false);
}

export function UserAnalyticsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAnalyticsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'test_taken_at': json['test_taken_at'] == null ? undefined : (new Date(json['test_taken_at'])),
        'average_score': json['average_score'] == null ? undefined : json['average_score'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'given_assessments': json['given_assessments'] == null ? undefined : json['given_assessments'],
        'upcoming_assessments': json['upcoming_assessments'] == null ? undefined : json['upcoming_assessments'],
    };
}

export function UserAnalyticsDtoToJSON(value?: UserAnalyticsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'test_taken_at': value['test_taken_at'] == null ? undefined : ((value['test_taken_at'] as any).toISOString()),
        'average_score': value['average_score'],
        'rank': value['rank'],
        'given_assessments': value['given_assessments'],
        'upcoming_assessments': value['upcoming_assessments'],
    };
}

