/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserListItemDto
 */
export interface UserListItemDto {
    /**
     * User ID
     * @type {string}
     * @memberof UserListItemDto
     */
    id: string;
    /**
     * User full name
     * @type {string}
     * @memberof UserListItemDto
     */
    full_name?: string | null;
    /**
     * User email
     * @type {string}
     * @memberof UserListItemDto
     */
    email: string;
    /**
     * User phone number
     * @type {string}
     * @memberof UserListItemDto
     */
    phone_number?: string | null;
    /**
     * Country code
     * @type {string}
     * @memberof UserListItemDto
     */
    country_code?: string | null;
    /**
     * Whether user account is active
     * @type {boolean}
     * @memberof UserListItemDto
     */
    is_active: boolean;
    /**
     * Whether email is verified
     * @type {boolean}
     * @memberof UserListItemDto
     */
    is_email_verified: boolean;
    /**
     * Whether phone is verified
     * @type {boolean}
     * @memberof UserListItemDto
     */
    is_phone_verified: boolean;
    /**
     * User creation timestamp
     * @type {Date}
     * @memberof UserListItemDto
     */
    created_at: Date;
    /**
     * User roles
     * @type {Array<string>}
     * @memberof UserListItemDto
     */
    roles: Array<string>;
    /**
     * Number of enrolled courses
     * @type {number}
     * @memberof UserListItemDto
     */
    enrolled_courses_count: number;
}

/**
 * Check if a given object implements the UserListItemDto interface.
 */
export function instanceOfUserListItemDto(value: object): value is UserListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    if (!('is_email_verified' in value) || value['is_email_verified'] === undefined) return false;
    if (!('is_phone_verified' in value) || value['is_phone_verified'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('enrolled_courses_count' in value) || value['enrolled_courses_count'] === undefined) return false;
    return true;
}

export function UserListItemDtoFromJSON(json: any): UserListItemDto {
    return UserListItemDtoFromJSONTyped(json, false);
}

export function UserListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'full_name': json['full_name'] == null ? undefined : json['full_name'],
        'email': json['email'],
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
        'country_code': json['country_code'] == null ? undefined : json['country_code'],
        'is_active': json['is_active'],
        'is_email_verified': json['is_email_verified'],
        'is_phone_verified': json['is_phone_verified'],
        'created_at': (new Date(json['created_at'])),
        'roles': json['roles'],
        'enrolled_courses_count': json['enrolled_courses_count'],
    };
}

export function UserListItemDtoToJSON(value?: UserListItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'full_name': value['full_name'],
        'email': value['email'],
        'phone_number': value['phone_number'],
        'country_code': value['country_code'],
        'is_active': value['is_active'],
        'is_email_verified': value['is_email_verified'],
        'is_phone_verified': value['is_phone_verified'],
        'created_at': ((value['created_at']).toISOString()),
        'roles': value['roles'],
        'enrolled_courses_count': value['enrolled_courses_count'],
    };
}

