/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationDetailsDto } from './PaginationDetailsDto';
import {
    PaginationDetailsDtoFromJSON,
    PaginationDetailsDtoFromJSONTyped,
    PaginationDetailsDtoToJSON,
} from './PaginationDetailsDto';
import type { UserListItemDto } from './UserListItemDto';
import {
    UserListItemDtoFromJSON,
    UserListItemDtoFromJSONTyped,
    UserListItemDtoToJSON,
} from './UserListItemDto';

/**
 * 
 * @export
 * @interface UserListResponseDto
 */
export interface UserListResponseDto {
    /**
     * List of users
     * @type {Array<UserListItemDto>}
     * @memberof UserListResponseDto
     */
    users: Array<UserListItemDto>;
    /**
     * Pagination details
     * @type {PaginationDetailsDto}
     * @memberof UserListResponseDto
     */
    pagination: PaginationDetailsDto;
}

/**
 * Check if a given object implements the UserListResponseDto interface.
 */
export function instanceOfUserListResponseDto(value: object): value is UserListResponseDto {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function UserListResponseDtoFromJSON(json: any): UserListResponseDto {
    return UserListResponseDtoFromJSONTyped(json, false);
}

export function UserListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserListItemDtoFromJSON)),
        'pagination': PaginationDetailsDtoFromJSON(json['pagination']),
    };
}

export function UserListResponseDtoToJSON(value?: UserListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'users': ((value['users'] as Array<any>).map(UserListItemDtoToJSON)),
        'pagination': PaginationDetailsDtoToJSON(value['pagination']),
    };
}

