/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAssessmentData
 */
export interface UserAssessmentData {
    /**
     * Assessment ID
     * @type {string}
     * @memberof UserAssessmentData
     */
    id: string;
    /**
     * Assessment name
     * @type {string}
     * @memberof UserAssessmentData
     */
    status: string;
    /**
     * Assessment started at
     * @type {string}
     * @memberof UserAssessmentData
     */
    started_at?: string | null;
    /**
     * Assessment completed at
     * @type {string}
     * @memberof UserAssessmentData
     */
    completed_at?: string | null;
    /**
     * Assessment total score
     * @type {number}
     * @memberof UserAssessmentData
     */
    total_score?: number | null;
    /**
     * Assessment is assessed
     * @type {boolean}
     * @memberof UserAssessmentData
     */
    is_assessed: boolean;
    /**
     * Assessment percentage score
     * @type {number}
     * @memberof UserAssessmentData
     */
    percentage_score?: number | null;
    /**
     * Assessment feedback
     * @type {string}
     * @memberof UserAssessmentData
     */
    feedback?: string | null;
    /**
     * Assessment scheduled at
     * @type {string}
     * @memberof UserAssessmentData
     */
    scheduled_at: string;
    /**
     * Assessment weak areas
     * @type {Array<string>}
     * @memberof UserAssessmentData
     */
    weak_areas: Array<string>;
    /**
     * Assessment strong areas
     * @type {Array<string>}
     * @memberof UserAssessmentData
     */
    strong_areas: Array<string>;
    /**
     * Assessment created at
     * @type {Date}
     * @memberof UserAssessmentData
     */
    created_at: Date;
}

/**
 * Check if a given object implements the UserAssessmentData interface.
 */
export function instanceOfUserAssessmentData(value: object): value is UserAssessmentData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('is_assessed' in value) || value['is_assessed'] === undefined) return false;
    if (!('scheduled_at' in value) || value['scheduled_at'] === undefined) return false;
    if (!('weak_areas' in value) || value['weak_areas'] === undefined) return false;
    if (!('strong_areas' in value) || value['strong_areas'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function UserAssessmentDataFromJSON(json: any): UserAssessmentData {
    return UserAssessmentDataFromJSONTyped(json, false);
}

export function UserAssessmentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAssessmentData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'started_at': json['started_at'] == null ? undefined : json['started_at'],
        'completed_at': json['completed_at'] == null ? undefined : json['completed_at'],
        'total_score': json['total_score'] == null ? undefined : json['total_score'],
        'is_assessed': json['is_assessed'],
        'percentage_score': json['percentage_score'] == null ? undefined : json['percentage_score'],
        'feedback': json['feedback'] == null ? undefined : json['feedback'],
        'scheduled_at': json['scheduled_at'],
        'weak_areas': json['weak_areas'],
        'strong_areas': json['strong_areas'],
        'created_at': (new Date(json['created_at'])),
    };
}

export function UserAssessmentDataToJSON(value?: UserAssessmentData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': value['status'],
        'started_at': value['started_at'],
        'completed_at': value['completed_at'],
        'total_score': value['total_score'],
        'is_assessed': value['is_assessed'],
        'percentage_score': value['percentage_score'],
        'feedback': value['feedback'],
        'scheduled_at': value['scheduled_at'],
        'weak_areas': value['weak_areas'],
        'strong_areas': value['strong_areas'],
        'created_at': ((value['created_at']).toISOString()),
    };
}

