/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileDto } from './UserProfileDto';
import {
    UserProfileDtoFromJSON,
    UserProfileDtoFromJSONTyped,
    UserProfileDtoToJSON,
} from './UserProfileDto';

/**
 * 
 * @export
 * @interface UserProfileResponseDto
 */
export interface UserProfileResponseDto {
    /**
     * User profile data
     * @type {UserProfileDto}
     * @memberof UserProfileResponseDto
     */
    profile: UserProfileDto;
}

/**
 * Check if a given object implements the UserProfileResponseDto interface.
 */
export function instanceOfUserProfileResponseDto(value: object): value is UserProfileResponseDto {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function UserProfileResponseDtoFromJSON(json: any): UserProfileResponseDto {
    return UserProfileResponseDtoFromJSONTyped(json, false);
}

export function UserProfileResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': UserProfileDtoFromJSON(json['profile']),
    };
}

export function UserProfileResponseDtoToJSON(value?: UserProfileResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'profile': UserProfileDtoToJSON(value['profile']),
    };
}

