/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAnalyticsDto } from './UserAnalyticsDto';
import {
    UserAnalyticsDtoFromJSON,
    UserAnalyticsDtoFromJSONTyped,
    UserAnalyticsDtoToJSON,
} from './UserAnalyticsDto';

/**
 * 
 * @export
 * @interface UserAnalyticsResponseDto
 */
export interface UserAnalyticsResponseDto {
    /**
     * User analytics data
     * @type {UserAnalyticsDto}
     * @memberof UserAnalyticsResponseDto
     */
    analytics: UserAnalyticsDto;
}

/**
 * Check if a given object implements the UserAnalyticsResponseDto interface.
 */
export function instanceOfUserAnalyticsResponseDto(value: object): value is UserAnalyticsResponseDto {
    if (!('analytics' in value) || value['analytics'] === undefined) return false;
    return true;
}

export function UserAnalyticsResponseDtoFromJSON(json: any): UserAnalyticsResponseDto {
    return UserAnalyticsResponseDtoFromJSONTyped(json, false);
}

export function UserAnalyticsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAnalyticsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'analytics': UserAnalyticsDtoFromJSON(json['analytics']),
    };
}

export function UserAnalyticsResponseDtoToJSON(value?: UserAnalyticsResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'analytics': UserAnalyticsDtoToJSON(value['analytics']),
    };
}

