/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyForgotPasswordOtpResponseDto
 */
export interface VerifyForgotPasswordOtpResponseDto {
    /**
     * 
     * @type {string}
     * @memberof VerifyForgotPasswordOtpResponseDto
     */
    message: string;
    /**
     * Access token after OTP verification
     * @type {string}
     * @memberof VerifyForgotPasswordOtpResponseDto
     */
    token: string;
}

/**
 * Check if a given object implements the VerifyForgotPasswordOtpResponseDto interface.
 */
export function instanceOfVerifyForgotPasswordOtpResponseDto(value: object): value is VerifyForgotPasswordOtpResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function VerifyForgotPasswordOtpResponseDtoFromJSON(json: any): VerifyForgotPasswordOtpResponseDto {
    return VerifyForgotPasswordOtpResponseDtoFromJSONTyped(json, false);
}

export function VerifyForgotPasswordOtpResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyForgotPasswordOtpResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'token': json['token'],
    };
}

export function VerifyForgotPasswordOtpResponseDtoToJSON(value?: VerifyForgotPasswordOtpResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'token': value['token'],
    };
}

