/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyForgotPasswordOtpResponseDto } from './VerifyForgotPasswordOtpResponseDto';
import {
    VerifyForgotPasswordOtpResponseDtoFromJSON,
    VerifyForgotPasswordOtpResponseDtoFromJSONTyped,
    VerifyForgotPasswordOtpResponseDtoToJSON,
} from './VerifyForgotPasswordOtpResponseDto';

/**
 * 
 * @export
 * @interface VerifyForgotPasswordOtpApiResponse
 */
export interface VerifyForgotPasswordOtpApiResponse {
    /**
     * 
     * @type {number}
     * @memberof VerifyForgotPasswordOtpApiResponse
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof VerifyForgotPasswordOtpApiResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyForgotPasswordOtpApiResponse
     */
    message: string;
    /**
     * 
     * @type {VerifyForgotPasswordOtpResponseDto}
     * @memberof VerifyForgotPasswordOtpApiResponse
     */
    data?: VerifyForgotPasswordOtpResponseDto | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyForgotPasswordOtpApiResponse
     */
    error?: string | null;
    /**
     * 
     * @type {object}
     * @memberof VerifyForgotPasswordOtpApiResponse
     */
    meta?: object | null;
}

/**
 * Check if a given object implements the VerifyForgotPasswordOtpApiResponse interface.
 */
export function instanceOfVerifyForgotPasswordOtpApiResponse(value: object): value is VerifyForgotPasswordOtpApiResponse {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function VerifyForgotPasswordOtpApiResponseFromJSON(json: any): VerifyForgotPasswordOtpApiResponse {
    return VerifyForgotPasswordOtpApiResponseFromJSONTyped(json, false);
}

export function VerifyForgotPasswordOtpApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyForgotPasswordOtpApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'status': json['status'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : VerifyForgotPasswordOtpResponseDtoFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function VerifyForgotPasswordOtpApiResponseToJSON(value?: VerifyForgotPasswordOtpApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': value['statusCode'],
        'status': value['status'],
        'message': value['message'],
        'data': VerifyForgotPasswordOtpResponseDtoToJSON(value['data']),
        'error': value['error'],
        'meta': value['meta'],
    };
}

