/* tslint:disable */
/* eslint-disable */
/**
 * mockAI
 * The Node based REST API documentation for mockAI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyForgotPasswordOtpDto
 */
export interface VerifyForgotPasswordOtpDto {
    /**
     * OTP received via email
     * @type {number}
     * @memberof VerifyForgotPasswordOtpDto
     */
    otp: number;
}

/**
 * Check if a given object implements the VerifyForgotPasswordOtpDto interface.
 */
export function instanceOfVerifyForgotPasswordOtpDto(value: object): value is VerifyForgotPasswordOtpDto {
    if (!('otp' in value) || value['otp'] === undefined) return false;
    return true;
}

export function VerifyForgotPasswordOtpDtoFromJSON(json: any): VerifyForgotPasswordOtpDto {
    return VerifyForgotPasswordOtpDtoFromJSONTyped(json, false);
}

export function VerifyForgotPasswordOtpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyForgotPasswordOtpDto {
    if (json == null) {
        return json;
    }
    return {
        
        'otp': json['otp'],
    };
}

export function VerifyForgotPasswordOtpDtoToJSON(value?: VerifyForgotPasswordOtpDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'otp': value['otp'],
    };
}

